### PR TITLE
Update logic to determine which jobs use the cache

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Remove the special case for not downloading cache data for some continuous jobs.

Cache the following:

1. All release jobs except unprovisioned, mac x86 and weekly

2. continuous, experimental and nightly versions of:
* linux-focal-clang-bazel-*-leak-sanitizer
* linux-focal-clang-bazel-*-debug
* linux-jammy-gcc-bazel-*-debug
* mac-arm-monterey-clang-bazel-*-debug

Resolves https://github.com/RobotLocomotion/drake/issues/19341

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/224)

### CODE REVIEW

**Review by mwoehlke-kitware — COMMENTED** [review]
The `linux-focal-clang` and `linux-jammy-gcc` jobs populate the cache, but `linux-focal-gcc` and `linux-jammy-clang` do not? That seems like a rather arbitrary choice.

Also, I did not realize that experimental jobs populate the cache?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/224#-:-NVp6MGfDAPLhYMeHdpx:b-oc0zer)* status: 1 of 2 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
For jobs where `REMOTE_CACHE` is true, experimental jobs read from the cache, nightly jobs write to the cache, and continuous jobs do both. That logic is in `cmake.cmake` and `bazel.cmake`. Perhaps we need to make all the decisions in this file (e.g. create variables like `WRITE_REMOTE_CACHE` and `READ_REMOTE_CACHE`).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/224#-:-NVpLvv28S85fRofNeRV:ba33loo)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/224#-NVpMqDW20qqHxrY6Id6:-NVpMqDW20qqHxrY6Id7:b-98p1ka) (no related file):*
(Starting a new discussion)

_The `linux-focal-clang` and `linux-jammy-gcc` jobs populate the cache, but `linux-focal-gcc` and `linux-jammy-clang` do not? That seems like a rather arbitrary choice._

`linux-focal-gcc-bazel-continuous-debug` , `linux-focal-gcc-bazel-continuous-debug`,`linux-jammy-clang-bazel-continuous-debug` and `linux-jammy-clang-bazel-continuous-debug` don't exist... Should the `drake-ci` logic care about that? Or just specify that they _should_ be cached if they were to exist?

___

**Comment by mwoehlke-kitware** [comment]
> [various jobs] don't exist... Should the drake-ci logic care about that? Or just specify that they should be cached if they were to exist?

Given the stated "when to use cache" rationale in https://github.com/RobotLocomotion/drake/issues/19341#issuecomment-1555091611, I lean toward writing the regexes to match those jobs. Alternatively / at the least, I think it would help to have a comment *why* we aren't matching those.

**Comment by BetsyMcPhail** [comment]
Replaced by #231

**Pull request closed without merging**
