### PR TITLE
Use Bazel config for compiler selection

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Use the recently introduced Bazel configuration mechanism for compiler selection. This effectively moves most of the relevant logic to the Drake repository, which will especially allow changing what version of Clang is used on Ubuntu without needing to make changes here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/150)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The file `step-report-bazel-command.cmake` might also need an update to nix `DASHBOARD_BAZEL_ENV`.

**Comment by mwoehlke-kitware** [comment]
> The file `step-report-bazel-command.cmake` might also need an update to nix `DASHBOARD_BAZEL_ENV`.

Yup; good catch! (Done.)

**Comment by mwoehlke-kitware** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0ffXjn6yhMQ2DN4jdO:bk0r97v) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Possibly this loses the compiler setting for Ubuntu CMake builds like https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-focal-clang-cmake-continuous-release/ 

The `--config` fragment is only added to Bazel builds; the CMake builds will all be the empty (i.e., host) default now, I think?

We might still need a CMake fragment in `drake` for the `driver/configurations/cmake.cmake` to use, or find a way to thread the `--config` into CMake CI somehow.
</blockquote></details>

No; CMake builds always forward the compiler that CMake is using. Probably that means the compiler selection logic needs to be relocated to be CMake-specific rather than removing it entirely... which means we still have the situation that the compiler is partly specified by this repo :cry:. Unless we rip out the logic to pass the CMake compiler along to Bazel.

**Comment by jwnimmer-tri** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0fjRvC4RIUo0X6erjP:b7srkzs) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

No; CMake builds always forward the compiler that CMake is using. Probably that means the compiler selection logic needs to be relocated to be CMake-specific rather than removing it entirely... which means we still have the situation that the compiler is partly specified by this repo :cry:. Unless we rip out the logic to pass the CMake compiler along to Bazel.
</blockquote></details>

It's possible that the CI jobs where this question is relevant are useless anyway.  Let me check on that before we try to fix it.

**Comment by jwnimmer-tri** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0fk2JC0JkiWBVSQAFa:b-c8g70i) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's possible that the CI jobs where this question is relevant are useless anyway.  Let me check on that before we try to fix it.
</blockquote></details>

Yeah.  I don't see any merit to running `linux-focal-(unprovisioned-)clang-cmake(..)` builds.  Using _only_ the default host compiler (gcc on linux) when running CMake builds seems sufficient.

WDYT about removing the problematic build definition from Jenkins, and then this issue evaporates?

**Comment by mwoehlke-kitware** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0fkyxQ07XImmhM0X-c:b1zgr5y) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah.  I don't see any merit to running `linux-focal-(unprovisioned-)clang-cmake(..)` builds.  Using _only_ the default host compiler (gcc on linux) when running CMake builds seems sufficient.

WDYT about removing the problematic build definition from Jenkins, and then this issue evaporates?
</blockquote></details>

No objection *here*. @BetsyMcPhail, any thoughts? (For now, I'll amend the commit description to note this "deficiency".)

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/150)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail, @jwnimmer-tri, and @mwoehlke-kitware)

___
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0fnLUDDg9A-8HNXg78:bn8yq2u) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

No objection *here*. @BetsyMcPhail, any thoughts? (For now, I'll amend the commit description to note this "deficiency".)
</blockquote></details>

I'm good with removing redundant / confusing builds. I don't think it's worth adding more complexity to just support the `linux-focal-(unprovisioned-)clang-cmake(..)` jobs.

**Comment by mwoehlke-kitware** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0gEC4b1h4CDUJTFZzZ:bji2nb8) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I'm good with removing redundant / confusing builds. I don't think it's worth adding more complexity to just support the `linux-focal-(unprovisioned-)clang-cmake(..)` jobs.
</blockquote></details>

Okay, so, due to other complications, the `linux-focal-(unprovisioned-)clang-cmake(..)` jobs can stay.

This PR is going to need some reworking.

**Comment by mwoehlke-kitware** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0gQYdj7BTWX4l3E39Z:bv6ea1y) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay, so, due to other complications, the `linux-focal-(unprovisioned-)clang-cmake(..)` jobs can stay.

This PR is going to need some reworking.
</blockquote></details>

Okay, this has been overhauled to retain most of the existing logic, but extract the compilers from Bazel. This means that the cache key computation does not need to be rewritten, and we will still pass the compiler through CMake builds (but we now ask Bazel how `CC` and `CXX` should be set based on `--config=${COMPILER}`).

Note that this depends on RobotLocomotion/drake#17050, which will need to land first.

**Comment by mwoehlke-kitware** [comment]
I think this also depends on RobotLocomotion/drake#17062 and possibly some further tweaking on the CI side.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 6 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/150)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0rB6_s8QKG6uq8Uexa:bdrtp6z) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
> linux-focal-(unprovisioned-)clang-cmake(..)

Filed as https://github.com/RobotLocomotion/drake/issues/17073 now.  I'll mark this thread as closed.

**Comment by mwoehlke-kitware** [comment]
Okay, I *think* this is working now. We should probably try to run a rather wide sampling of tests beforehand. Here's an attempt to do so:

- https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-clang-bazel-experimental-release/376/
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-monterey-clang-cmake-experimental-everything-release/3/
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-monterey-clang-bazel-experimental-release/45/console
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-gcc-bazel-experimental-release/10170/
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-gcc-cmake-experimental-debug/3/
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-unprovisioned-clang-bazel-experimental-debug/10/
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-big-sur-unprovisioned-clang-bazel-experimental-release/51/
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/15/

All successful (unless I missed something).

I don't think there's much to be gained from coverage of what optional bits are enabled, since any breakage is likely to happen either before or just at the start of the build proper, but I tried to cover a decent smattering of Linux vs. macOS, gcc vs. clang, and the various "exotic" builds (CMake, wheel, unprovisioned).

**Comment by mwoehlke-kitware** [comment]
*[`driver/compiler.cmake` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-N0fPPCO6KqDY6IHMcTg:-N0rOqWL4Eqjsb9NiqM6:b-b90wom) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/compiler.cmake#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> linux-focal-(unprovisioned-)clang-cmake(..)

Filed as https://github.com/RobotLocomotion/drake/issues/17073 now.  I'll mark this thread as closed.
</blockquote></details>

ACK on the thread closure. However, I'll repeat: since I ended up changing the approach for reasons related to computing the build cache key, this is also no longer an issue. Due to that, it turns out *all* builds need to extract "CC", even if it is `--config=${COMPILER}` that is ultimately passed to Bazel. Thus, the CMake builds can grab `CC`/`CXX` from `bazel --config=${COMPILER}` (so, not hard coded in drake-ci, which was the goal) and pass that into CMake, which then passes them (using direct environment variables, *not* `--config`) back to Bazel. So the clang-cmake builds work just fine, and also test that passing a compiler to CMake gets propagated into Bazel.

**Comment by mwoehlke-kitware** [comment]
FYI, this is still waiting on an LGTM, and also is still reporting a change requested by @jwnimmer-tri.

**Review by jwnimmer-tri — APPROVED** [review]
Oops, unless it's "Assigned" to me, it doesn't show up in my dashboard.  ("Review Requested" is not sufficient, on its own.)

:lgtm:

> Reviewed 1 of 4 files at r1, 4 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-:-N14pJzUDbd6pXXPWseR:b-bnf34z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
@jwnimmer-tri, it wasn't necessarily *assigned* to you, anyway; in fact, it'd be great if @BetsyMcPhail is available to take another look before landing this. Problem from you was more that Reviewable was insisting you were blocking it for reasons which were not clear.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

The set of test jobs looks comprehensive

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/150#-:-N15-fk9-tIngOQN5WH6:b-e35zk1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Pull request merged**
