### PR TITLE
[sonoma] Bypass SSL problems with CURL_SSL_BACKEND=SecureTransport

### PR DESCRIPTION
**Pull request by svenevs**
Relates: https://github.com/RobotLocomotion/drake/issues/20718

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`driver/environment.cmake` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-NnQ59P27sBpFfNENtv_:-NnQ59P3B-1TutbiP4Fr:b-9klsg0) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/7fccad7b7a0918ecc6605362580ea2d1b0f97796/driver/environment.cmake#L92)):*
> ```CMake
> # hack to get CDash job submissions to work.
> if(DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME STREQUAL "sonoma")
>   set(ENV{CURL_SSL_BACKEND} "SecureTransport")
> ```

working, test build here: https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/29/console

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`driver/environment.cmake` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-NnQ59P27sBpFfNENtv_:-NnQ6OwI4BxfQtkY3qeR:b-f42iui) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/7fccad7b7a0918ecc6605362580ea2d1b0f97796/driver/environment.cmake#L92)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, test build here: https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/29/console
</blockquote></details>

`\[2:32:53 PM\]  -- Submitted to CDash with build id 1754171`

looks good, I'm going to confirm it goes back to failing on a different backend

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`driver/environment.cmake` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-NnQ59P27sBpFfNENtv_:-NnQ6kHU4O_YSKC1iDmr:b-w6p5vh) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/7fccad7b7a0918ecc6605362580ea2d1b0f97796/driver/environment.cmake#L92)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

`\[2:32:53 PM\]  -- Submitted to CDash with build id 1754171`

looks good, I'm going to confirm it goes back to failing on a different backend
</blockquote></details>

https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/30/consoleFull is the `OpenSSL` backend instead which AFAIU is the one that is broken right now

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`driver/environment.cmake` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-NnQ59P27sBpFfNENtv_:-NnQ89oK5DoClpe_ktVy:b-w96lyt) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/7fccad7b7a0918ecc6605362580ea2d1b0f97796/driver/environment.cmake#L92)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/30/consoleFull is the `OpenSSL` backend instead which AFAIU is the one that is broken right now
</blockquote></details>

```
\[2:40:54 PM\]     Error when uploading file: /Users/admin/workspace/mac-arm-sonoma-clang-bazel-experimental-release/\_bazel\_admin/Testing/20240105-1936/Update.xml
\[2:40:54 PM\]     Error message was: LibreSSL/3.3.6: error:0DFFF0A1:lib(13):func(4095):reason(161)
\[2:40:54 PM\]     Problems when submitting via HTTP
\[2:40:54 PM\]  CMake Warning at /Users/admin/workspace/mac-arm-sonoma-clang-bazel-experimental-release/ci/driver
```

Mmmk, problem is understood well enough now, almost guaranteed the fix will land in brew (eventually) and then when things update down the road we can just remove this setting.  Only possible change in the future is maybe it'll start hitting Ventura, but for now we're just special-casing what we need to.

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for review please.  CI results should come back in fairly quickly, I'd like to merge this fix as is, and update the drake issue to stay open and explain in the top level description the plan of attack (revert this hack when we re-provision sonoma  next).

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-:-NnQ8fhV4rkBDRJrjtAp:b-bp6iuv)* status: all files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @svenevs)

___
*[`driver/environment.cmake` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-NnQ59P27sBpFfNENtv_:-NnQ8Zh013XiAzmZ7acX:bemyc2l) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/7fccad7b7a0918ecc6605362580ea2d1b0f97796/driver/environment.cmake#L92)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

```
\[2:40:54 PM\]     Error when uploading file: /Users/admin/workspace/mac-arm-sonoma-clang-bazel-experimental-release/\_bazel\_admin/Testing/20240105-1936/Update.xml
\[2:40:54 PM\]     Error message was: LibreSSL/3.3.6: error:0DFFF0A1:lib(13):func(4095):reason(161)
\[2:40:54 PM\]     Problems when submitting via HTTP
\[2:40:54 PM\]  CMake Warning at /Users/admin/workspace/mac-arm-sonoma-clang-bazel-experimental-release/ci/driver
```

Mmmk, problem is understood well enough now, almost guaranteed the fix will land in brew (eventually) and then when things update down the road we can just remove this setting.  Only possible change in the future is maybe it'll start hitting Ventura, but for now we're just special-casing what we need to.
</blockquote></details>

https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/31/consoleFull is the next build to confirm, will resolve this when it successfully submits to CDash with a build id again.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail and @svenevs)

___
*[`driver/environment.cmake` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261#-NnQ59P27sBpFfNENtv_:-NnQAB5kB-GHAATK10Ng:bx2czgg) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/7fccad7b7a0918ecc6605362580ea2d1b0f97796/driver/environment.cmake#L92)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/31/consoleFull is the next build to confirm, will resolve this when it successfully submits to CDash with a build id again.
</blockquote></details>

done: `\[2:49:43 PM\]  -- Submitted to CDash with build id 1754173`

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @svenevs)

**Pull request merged**
