### PR TITLE
coverage: Enable kcov parallel testing schedule

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: drake issue #10617

If the kcov_tool is present in drake, then invoke it to merge results into the
traditional location, bazel-kcov, before publishing. If kcov_tool is absent,
coverage publishing work exactly as before.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/116)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/116)* status: 0 of 1 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLZNpEM9ycHRIYXYmuQ:b4yglcp) (no related file):*
I believe that this patch will work even without https://github.com/RobotLocomotion/drake/pull/14294 . However, I have no idea how to properly test this change.

---

**Review by rpoyner-tri — COMMENTED** [review]
+@jamiesnape for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-:-MLZOf1REcS_662Ddq-j:b1vx91e)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jamiesnape)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: from my perspective.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-:-MLjs1BN82sGUG7us3Ss:b-rc6otd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLjs-2W-OPC5NI_nDQ7:b-fd3or9) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I believe that this patch will work even without https://github.com/RobotLocomotion/drake/pull/14294 . However, I have no idea how to properly test this change.
</blockquote></details>

I think we can merge it and then revert in case it's a problem.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLju2WpEkBTk9dKfdyI:b-r73tj1) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we can merge it and then revert in case it's a problem.
</blockquote></details>

Ok then, gents, I'll hit the merge button and drop a note into #buildcop just in case things should go south.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLjw25TBI0maEDg89Z4:bhwk4pg) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ok then, gents, I'll hit the merge button and drop a note into #buildcop just in case things should go south.
</blockquote></details>

Explicit post-merge test build:
https://drake-jenkins.csail.mit.edu/view/Coverage/job/linux-bionic-clang-bazel-experimental-everything-coverage/18/

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLmf2_35tJKsw9AMTCh:b-9g6wo1) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Explicit post-merge test build:
https://drake-jenkins.csail.mit.edu/view/Coverage/job/linux-bionic-clang-bazel-experimental-everything-coverage/18/
</blockquote></details>

Huh. So that build maybe didn't teach us anything because it hit the overall jenkins timeout. I'll have to look deeper to see if any of the postprocessing got executed.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLmfUKX5nLWq6e1ra3x:b-vs7ueq) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Huh. So that build maybe didn't teach us anything because it hit the overall jenkins timeout. I'll have to look deeper to see if any of the postprocessing got executed.
</blockquote></details>

Nope. Nothing. Died during bazel test phase.

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/116#-MLZNpELE1nBJ0hho_7n:-MLmgWT-3bJUoL3B9192:bu39llx) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Nope. Nothing. Died during bazel test phase.
</blockquote></details>

At this point, the nightlies (still pending) + the Drake PR 14294 builds (as adiscussed in the PR) are the most helpful sources of feedback.

---

**Pull request merged**
