### PR TITLE
Remove caching for x86 Mac jobs

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/19097

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@svenevs for review please. As the "special" case has effectively flipped from ARM to x86, it made the logic easier to set `APPLE_X86` rather than `APPLE_ARM64`

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-:-NRnqpg-AUxpucD9GF4Q:be5878a)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @svenevs)

**Review by svenevs — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211)* status: all files reviewed, 2 unresolved discussions (waiting on @BetsyMcPhail)

___
*[`driver/distribution.cmake` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoBOwnESiRUmbTjd0V:-NRoBOwnESiRUmbTjd0W:b-i58u25) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/distribution.cmake#L70)):*
> ```CMake
>   endif()
>   if(APPLE_ARCHITECTURE STREQUAL "arm64")
>     set(APPLE_X86 OFF)
> ```

I want both variables, lets set both `APPLE_X86` and `APPLE_ARM64`?  (pending other thread on `cache.cmake`)
___
*[`driver/environment.cmake` line 164 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoDCu_DcuPqSHxGUpF:-NRoDCu_DcuPqSHxGUpG:bd64fmv) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/environment.cmake#L164)):*
> ```CMake
> endif()
> 
> # Special case Mac ARM jobs that do not match the above patterns but we want cached.
> ```

fyi manual oversight of this change is too tedious, I have scraped all jobs that are cached vs not (51 cached, 304 not).  after we merge this and a full 24 hour cycle has passed (to include nightly and continuous) we will re-scrape and see if we took away too much
___
*[`driver/environment.cmake` line 240 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoBgqlBXhs1AImjWqO:-NRoBgqlBXhs1AImjWqP:b-m3qxnt) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/environment.cmake#L240)):*
> ```CMake
> if(REGEX_MATCH_RESULT)
>   if(APPLE)
>     if(DISTRIBUTION STREQUAL "monterey")
> ```

fyi we'll need to restore this logic at some point depending on the x86 saga, maybe it is better to just leave it split up by distribution so we have the skeleton and it is easier to change e.g., just arm64 to ventura?
___
*[`driver/configurations/cache.cmake` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoC1vyDGqcnhQoJN_X:-NRoC1vyDGqcnhQoJN_Y:bo8fvy0) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/configurations/cache.cmake#L49)):*
> ```CMake
>   list(APPEND DASHBOARD_TEMPORARY_FILES DASHBOARD_FILE_DOWNLOAD_TEMP)
> 
>   if(APPLE)
> ```

If any of the `cache.cmake` logic is messed up (intentional or accident) you can end up with an x86 job trying to use the arm64 cache.

`if(APPLE AND NOT APPLE_X86)` is one option, but I would greatly prefer we do

```cmake
if(APPLE)
  if(APPLE_ARM64)
    set(DASHBOARD_REMOTE_CACHE "http://10.221.188.9:6060")
  else()
    fatal("Apple x86 jobs should not be cached.")
  endif()
else()
  set(DASHBOARD_REMOTE_CACHE "http://172.31.20.109")
endif()
```
___
*[`driver/configurations/bazel/step-create-package-archive.cmake` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoD1T375GjHvZBql2-:-NRoD1T375GjHvZBql20:bx40uo0) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/configurations/bazel/step-create-package-archive.cmake#L57)):*
> ```CMake
>     file(WRITE /opt/drake/share/doc/drake/VERSION.TXT "${DASHBOARD_PACKAGE_DATE_TIME} ${DASHBOARD_PACKAGE_COMMIT}")
>     if(APPLE)
>       if(APPLE_X86)
> ```

fyi i'm ambivalent to this change, it can stay like this even if you bring back the `APPLE_ARM64` variable.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211)* status: all files reviewed, 2 unresolved discussions (waiting on @svenevs)

___
*[`driver/distribution.cmake` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoBOwnESiRUmbTjd0V:-NRoFNPd4Ob3cDxCqExx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/distribution.cmake#L70)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I want both variables, lets set both `APPLE_X86` and `APPLE_ARM64`?  (pending other thread on `cache.cmake`)
</blockquote></details>

Done.
___
*[`driver/configurations/cache.cmake` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoC1vyDGqcnhQoJN_X:-NRoFyqE1AsjaKBpQi5j:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/configurations/cache.cmake#L49)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

If any of the `cache.cmake` logic is messed up (intentional or accident) you can end up with an x86 job trying to use the arm64 cache.

`if(APPLE AND NOT APPLE_X86)` is one option, but I would greatly prefer we do

```cmake
if(APPLE)
  if(APPLE_ARM64)
    set(DASHBOARD_REMOTE_CACHE "http://10.221.188.9:6060")
  else()
    fatal("Apple x86 jobs should not be cached.")
  endif()
else()
  set(DASHBOARD_REMOTE_CACHE "http://172.31.20.109")
endif()
```
</blockquote></details>

Done.

**Review by svenevs — APPROVED** [review]
:lgtm: confirmatory builds:


### mac-arm-monterey-clang-bazel-experimental-release

https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/96/consoleFull

This job is correctly cached before and after this PR: 

```
[4:51:18 PM]    ------------------------------------------------------------------------------
[4:51:18 PM]    REMOTE_CACHE_KEY_VERSION       = v2
[4:51:18 PM]    REMOTE_CACHE_KEY               = 9d66b5aeec51c5820e8d7fd5930c2708b9f5842fd12d2adf0fddcc78248ad194
[4:51:18 PM]    ------------------------------------------------------------------------------
```

:heavy_check_mark: `--remote_cache=http://10.221.188.9:6060/v2/9d66b5aeec51c5820e8d7fd5930c2708b9f5842fd12d2adf0fddcc78248ad194`

### mac-arm-monterey-clang-bazel-experimental-release

This job is correctly **not** cached anymore.  Prior to this PR, it was.

https://drake-jenkins.csail.mit.edu/job/mac-x86-monterey-clang-bazel-experimental-release/59/consoleFull

```
[4:54:14 PM]    ------------------------------------------------------------------------------
[4:54:14 PM]    REMOTE_CACHE_KEY_VERSION       = 
[4:54:14 PM]    REMOTE_CACHE_KEY               = 
[4:54:14 PM]    ------------------------------------------------------------------------------
```

NOTE: job cancelled as it past the point of running CMake changes in this PR.

:heavy_check_mark: No `--remote_cache` in build log.

### linux-focal-gcc-bazel-experimental-release

https://drake-jenkins.csail.mit.edu/job/linux-focal-gcc-bazel-experimental-release/12641/consoleFull

This job is correctly cached before and after this PR:

```
[4:54:30 PM]    ------------------------------------------------------------------------------
[4:54:30 PM]    REMOTE_CACHE_KEY_VERSION       = v2
[4:54:30 PM]    REMOTE_CACHE_KEY               = cb67ff18dcac882caa72e2fc2b57a1441356b2cd549580fbb6e53135d05be77d
[4:54:30 PM]    ------------------------------------------------------------------------------
```

:heavy_check_mark: `--remote_cache=http://172.31.20.109/v2/cb67ff18dcac882caa72e2fc2b57a1441356b2cd549580fbb6e53135d05be77d`

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-:-NRoHRe6BamXm-AOEFxM:bfk767h)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

___
*[`driver/distribution.cmake` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoBOwnESiRUmbTjd0V:-NRoGMqp9g7PexDEdUGy:bsz1b0x) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/distribution.cmake#L70)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM thanks!
___
*[`driver/configurations/cache.cmake` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/211#-NRoC1vyDGqcnhQoJN_X:-NRoHLSz1IbUbI79B-il:bsz1b0x) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/e283168dec8c9d0a94c7940751540eae59f48065/driver/configurations/cache.cmake#L49)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM thanks!

**Pull request merged**
