### PR TITLE
[wheel] Use the improved builder command line

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See https://github.com/RobotLocomotion/drake/pull/18999.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/208)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-arm-monterey-unprovisioned-clang-wheel-experimental-release/7/console

**Review by jwnimmer-tri — COMMENTED** [review]
+@BetsyMcPhail for review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/208#-:-NR5ZpoC-ZAugE-vMvrz:b-54lyo6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/208#-NR5Zrhf9z4nbrXvfSlk:-NR5Zrhf9z4nbrXvfSll:bekukxh) (no related file):*
Working

Once the build finishes, I want to double-check the console log that the tests actually did run.

___

**Comment by jwnimmer-tri** [comment]
Ping again @BetsyMcPhail  (or @svenevs?).

**Review by svenevs — APPROVED** [review]
-@BetsyMcPhail +@svenevs for review.

:lgtm: in addition to the tests output running as jeremy showed we have

```
[7:47:51 PM]  INFO: Build completed successfully, 4 total actions
[7:47:51 PM]  INFO: Running command line: bazel-bin/tools/wheel/builder --output-dir /opt/drake-wheel 0.0.2023.3.21.19.47.45+gitbac2bf5f
[7:47:52 PM]  Installing bash
```

my logs are happy :slightly_smiling_face:, `-t` flag was removed in favor of `--no-test` flag.  as a result, we should merge this now so that jeremy can remove the deprecated `-t` flag (only still exists for `drake-ci` now).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/208#-:-NRGcgx455F-DkhI6Jzg:b-9rwuid)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
