### PR TITLE
Remove redundant parts of the init_script

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21030

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
The following jobs were launched by editing the 'init_script' in Jenkins to point to this branch and specifying this PR as the `ci_sha1`.  

https://drake-jenkins.csail.mit.edu/view/Linux%20ARM/job/linux-arm-jammy-unprovisioned-gcc-bazel-experimental-everything-release/1/console
https://drake-jenkins.csail.mit.edu/view/Linux%20ARM/job/linux-arm-jammy-unprovisioned-gcc-bazel-experimental-packaging/1/console
https://drake-jenkins.csail.mit.edu/view/Linux%20ARM/job/linux-arm-jammy-unprovisioned-gcc-bazel-experimental-release/11/console
https://drake-jenkins.csail.mit.edu/view/Linux%20ARM/job/linux-arm-jammy-unprovisioned-gcc-wheel-experimental-release/1/console

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-:-NtH_h1LAivzvpPhRAyH:b-smcc1e)* status: 0 of 3 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
+@svenevs for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-:-NtHawU7EwN688I1Mb_x:b-m8sb1l)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @svenevs)

**Review by svenevs — APPROVED** [review]
:lgtm: with a small nit about the new ami script, it's great to be adding that in as something we can just run when baking the images!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-:-NtIX63ABODa_V9-7uiQ:byfi8s6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

___
*[`setup/ubuntu/ami_init_script` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-NtIWTU0BpRPhxyp3wG-:-NtIWTU0BpRPhxyp3wG0:b-m07eaq) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/73ff2dc2cb3b37f35c6643fc5b5e293b2844d759/setup/ubuntu/ami_init_script#L49)):*
> ```
>   openssh-client
> 
> update-java-alternatives --jre-headless -s java-1.17.0-openjdk-amd64
> ```

FYI the `amd64` part here is a quasi-issue given why this PR is happening.  It will need to be different for the new arm64 images.  But that does not necessarily need to get fixed in this PR.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

___
*[`setup/ubuntu/ami_init_script` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-NtIWTU0BpRPhxyp3wG-:-NtM4KKW0OhQTcf3yYgJ:b-gzbc0a) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/73ff2dc2cb3b37f35c6643fc5b5e293b2844d759/setup/ubuntu/ami_init_script#L49)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI the `amd64` part here is a quasi-issue given why this PR is happening.  It will need to be different for the new arm64 images.  But that does not necessarily need to get fixed in this PR.
</blockquote></details>

I don't think it's worth investing any time on a solution here. This script is run once every two years or so and can be edited by hand if needed.

**Review by BetsyMcPhail — COMMENTED** [review]
Before merging, doing a spot check of a few x86 Jammy jobs with the new script:
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-jammy-unprovisioned-gcc-cmake-experimental-release/19/
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-jammy-clang-bazel-experimental-everything-release/2441/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-:-NtM59cr8fMBdtR5TjAn:b-xfduyn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
It turns out that the Jammy unprovisioned image had not been setup following the documented process. I created a new image by running the commands in `ami_init_script`. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/268#-:-NtMnm6S2qs3oaj7s2wg:b-81yef9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Pull request merged**
