### PR TITLE
Remove unsupported SNOPT options

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/141)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/141#-:-Myn4wYjA4IfKmD_aU4o:bnyvoyh)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
Uh... I disclaim any ability to comment on whether removing these makes sense (platform reviewer?). That said, it looks like maybe there is some related cruft in `environment.cmake`?

**Comment by jwnimmer-tri** [comment]
The review here can be as simple as confirming that everything being removed is dead code.  We have a set of build names configured in CI.  If those names can never match the regex conditions checked here, then this is dead code and is a-ok to remove.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

**Review by mwoehlke-kitware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Pull request merged**
