### PR TITLE
Add CDash support for Bazel

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Note: This change requires Bazel 0.5.3+

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
Example: https://drake-cdash.csail.mit.edu/index.php?project=Drake&parentid=796610

**Comment by BetsyMcPhail** [comment]
Successful build sent to CDash: https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-unprovisioned-clang-bazel-experimental/24/

**Comment by jwnimmer-tri** [comment]
As of this PR, something like the following appears at the end of every Jenkins build of Drake:
```
-- Generating package list...
.........
ERROR: error loading package 'bazel-src/external/bazel_tools/third_party/jformatstring': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/third_party/checker_framework_javacutil': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/third_party/checker_framework_dataflow': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/tools/jdk': Extension file not found. Unable to load package for '//tools/jdk:alias_rules.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/tools/build_defs/pkg': Extension file not found. Unable to load package for '//tools/build_defs/pkg:pkg.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/tools/cpp': Extension file not found. Unable to load package for '//tools/cpp:alias_rules.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/src/main/protobuf': Extension file not found. Unable to load package for '//third_party/grpc:build_defs.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/tools/osx': Extension file not found. Unable to load package for '//tools/osx:alias_rules.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/bazel_tools/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
ERROR: error loading package 'bazel-src/external/optitrack_driver/lcmtypes': Extension file not found. Unable to load file '//tools:lcm.bzl': file doesn't exist or isn't a file
DEBUG: /home/ubuntu/.cache/bazel/_bazel_ubuntu/7d79f863c59b67ba7a1ab1641300f288/external/gurobi/BUILD:6:1: gurobi.bzl: The saved value of GUROBI_PATH is empty or unset; export GUROBI_PATH to the correct value.
WARNING: --keep_going specified, ignoring errors.  Results may be inaccurate
```

I think saying "ERROR" so much is likely to confuse users that their PRs or Continuous builds have errors.  Is there a way to either fix whatever is error-ing, or mute the output, or print some kind of header that explains to readers to ignore the errors?

**Comment by jamiesnape** [comment]
I am just reverting it for now. @BetsyMcPhail Can you look into this and create a new PR when it is fixed?

**Pull request merged**
