### PR TITLE
Ensure Java consistency on macOS

### PR DESCRIPTION
**Pull request by nicolecheetham**
Ensures the specific java version installed stays consistent throughout an entire job. This aims to prevent breakage from future Homebrew updates.

Also, removes the outdated --ignore-pinned argument

Towards: [#22089](https://github.com/RobotLocomotion/drake/issues/22089)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/299)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/299#-:-OC3r9ek8wcW-qi1Y2ZY:b-1dud86)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Comment by nicolecheetham** [comment]
The experimental job I have running to test this PR: https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-everything-release/

**Comment by nicolecheetham** [comment]
Testing again: https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-everything-release/18/

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/299#-:-OCeW0dt0AtHiVWrjMhI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nicolecheetham)

**Pull request merged**
