### PR TITLE
[jenkins] Update java version in conjunction with drake-jenkins

### PR DESCRIPTION
**Pull request by svenevs**
- [X] :no_entry_sign: :construction: :skull_and_crossbones: DO NOT MERGE (testing in progress) :skull_and_crossbones: :construction: :no_entry_sign: 
- [X] Get it working with java 11.  Keep updating ... get it working with Java 17.
- All provisioned images need to get fixed.
    - macOS getting finished in a followup.  This PR is blocking other linux jenkins testing at this point.
- [X] Remote cache version needs to get bumped.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/245)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/245)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`setup/ubuntu/install_prereqs` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/245#-NfYjF-o4xLATBRt67Hc:-NfYjF-o4xLATBRt67Hd:b-5305xa) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/4c0449d30ebb00b0864c9eb5eeecbd5d84b41bb9/setup/ubuntu/install_prereqs#L78)):*
> ```
> # TODO: where should this be going, in drake?  It's used to try and fetch snopt.
> apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy \
>   ssh-askpass
> ```

working, struggling a lot with ssh credential problems

```
\[9:32:25 PM\]  INFO: Repository snopt instantiated at:
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/WORKSPACE:8:22: in <toplevel>
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/default.bzl:430:29: in add\_default\_workspace
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/default.bzl:336:25: in add\_default\_repositories
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl:49:22: in snopt\_repository
\[9:32:25 PM\]  Repository rule \_snopt\_repository defined at:
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl:224:36: in <toplevel>
\[9:32:25 PM\]  **ERROR:** An error occurred during the fetch of repository 'snopt':
\[9:32:25 PM\]     Traceback (most recent call last):
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 182, column 35, in \_impl
\[9:32:25 PM\]  		updated\_attrs = \_setup\_git(repo\_ctx)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 73, column 29, in \_setup\_git
\[9:32:25 PM\]  		git\_repo\_info = git\_repo(repo\_ctx, str(repo\_ctx.path(".")))
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 91, column 12, in git\_repo
\[9:32:25 PM\]  		\_update(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 109, column 10, in \_update
\[9:32:25 PM\]  		fetch(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 143, column 13, in fetch
\[9:32:25 PM\]  		\_git(
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 179, column 15, in \_git
\[9:32:25 PM\]  		\_error(ctx.name, start + list(args), st.stderr)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 200, column 9, in \_error
\[9:32:25 PM\]  		fail("error running '%s' while working with @%s:\\n%s" % (command\_text, name, stderr))
\[9:32:25 PM\]  Error in fail: error running 'git fetch origin refs/heads/\*:refs/remotes/origin/\* refs/tags/\*:refs/tags/\*' while working with @snopt:
\[9:32:25 PM\]  ssh\_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
\[9:32:25 PM\]  Host key verification failed.
\[9:32:25 PM\]  fatal: Could not read from remote repository.
\[9:32:25 PM\]  
\[9:32:25 PM\]  Please make sure you have the correct access rights
\[9:32:25 PM\]  and the repository exists.
\[9:32:25 PM\]  **ERROR:** /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/WORKSPACE:8:22: fetching \_snopt\_repository rule //external:snopt: Traceback (most recent call last):
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 182, column 35, in \_impl
\[9:32:25 PM\]  		updated\_attrs = \_setup\_git(repo\_ctx)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 73, column 29, in \_setup\_git
\[9:32:25 PM\]  		git\_repo\_info = git\_repo(repo\_ctx, str(repo\_ctx.path(".")))
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 91, column 12, in git\_repo
\[9:32:25 PM\]  		\_update(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 109, column 10, in \_update
\[9:32:25 PM\]  		fetch(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 143, column 13, in fetch
\[9:32:25 PM\]  		\_git(
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 179, column 15, in \_git
\[9:32:25 PM\]  		\_error(ctx.name, start + list(args), st.stderr)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 200, column 9, in \_error
\[9:32:25 PM\]  		fail("error running '%s' while working with @%s:\\n%s" % (command\_text, name, stderr))
\[9:32:25 PM\]  Error in fail: error running 'git fetch origin refs/heads/\*:refs/remotes/origin/\* refs/tags/\*:refs/tags/\*' while working with @snopt:
\[9:32:25 PM\]  ssh\_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
\[9:32:25 PM\]  Host key verification failed.
\[9:32:25 PM\]  fatal: Could not read from remote repository.
\[9:32:25 PM\]  
\[9:32:25 PM\]  Please make sure you have the correct access rights
\[9:32:25 PM\]  and the repository exists.
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/245)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`setup/ubuntu/install_prereqs` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/245#-NfYjF-o4xLATBRt67Hc:-NfYoL35CjJ5S3zBHFzz:b8ripi2) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/4c0449d30ebb00b0864c9eb5eeecbd5d84b41bb9/setup/ubuntu/install_prereqs#L78)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, struggling a lot with ssh credential problems

```
\[9:32:25 PM\]  INFO: Repository snopt instantiated at:
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/WORKSPACE:8:22: in <toplevel>
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/default.bzl:430:29: in add\_default\_workspace
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/default.bzl:336:25: in add\_default\_repositories
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl:49:22: in snopt\_repository
\[9:32:25 PM\]  Repository rule \_snopt\_repository defined at:
\[9:32:25 PM\]    /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl:224:36: in <toplevel>
\[9:32:25 PM\]  **ERROR:** An error occurred during the fetch of repository 'snopt':
\[9:32:25 PM\]     Traceback (most recent call last):
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 182, column 35, in \_impl
\[9:32:25 PM\]  		updated\_attrs = \_setup\_git(repo\_ctx)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 73, column 29, in \_setup\_git
\[9:32:25 PM\]  		git\_repo\_info = git\_repo(repo\_ctx, str(repo\_ctx.path(".")))
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 91, column 12, in git\_repo
\[9:32:25 PM\]  		\_update(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 109, column 10, in \_update
\[9:32:25 PM\]  		fetch(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 143, column 13, in fetch
\[9:32:25 PM\]  		\_git(
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 179, column 15, in \_git
\[9:32:25 PM\]  		\_error(ctx.name, start + list(args), st.stderr)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 200, column 9, in \_error
\[9:32:25 PM\]  		fail("error running '%s' while working with @%s:\\n%s" % (command\_text, name, stderr))
\[9:32:25 PM\]  Error in fail: error running 'git fetch origin refs/heads/\*:refs/remotes/origin/\* refs/tags/\*:refs/tags/\*' while working with @snopt:
\[9:32:25 PM\]  ssh\_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
\[9:32:25 PM\]  Host key verification failed.
\[9:32:25 PM\]  fatal: Could not read from remote repository.
\[9:32:25 PM\]  
\[9:32:25 PM\]  Please make sure you have the correct access rights
\[9:32:25 PM\]  and the repository exists.
\[9:32:25 PM\]  **ERROR:** /media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/WORKSPACE:8:22: fetching \_snopt\_repository rule //external:snopt: Traceback (most recent call last):
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 182, column 35, in \_impl
\[9:32:25 PM\]  		updated\_attrs = \_setup\_git(repo\_ctx)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/src/tools/workspace/snopt/repository.bzl", line 73, column 29, in \_setup\_git
\[9:32:25 PM\]  		git\_repo\_info = git\_repo(repo\_ctx, str(repo\_ctx.path(".")))
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 91, column 12, in git\_repo
\[9:32:25 PM\]  		\_update(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 109, column 10, in \_update
\[9:32:25 PM\]  		fetch(ctx, git\_repo)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 143, column 13, in fetch
\[9:32:25 PM\]  		\_git(
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 179, column 15, in \_git
\[9:32:25 PM\]  		\_error(ctx.name, start + list(args), st.stderr)
\[9:32:25 PM\]  	File "/media/ephemeral0/ubuntu/workspace/linux-jammy-unprovisioned-gcc-bazel-experimental-release/\_bazel\_ubuntu/eca6c9dee17f54cc028ac3a847964bf3/external/bazel\_tools/tools/build\_defs/repo/git\_worker.bzl", line 200, column 9, in \_error
\[9:32:25 PM\]  		fail("error running '%s' while working with @%s:\\n%s" % (command\_text, name, stderr))
\[9:32:25 PM\]  Error in fail: error running 'git fetch origin refs/heads/\*:refs/remotes/origin/\* refs/tags/\*:refs/tags/\*' while working with @snopt:
\[9:32:25 PM\]  ssh\_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
\[9:32:25 PM\]  Host key verification failed.
\[9:32:25 PM\]  fatal: Could not read from remote repository.
\[9:32:25 PM\]  
\[9:32:25 PM\]  Please make sure you have the correct access rights
\[9:32:25 PM\]  and the repository exists.
```
</blockquote></details>

Sigh, it seems it just got stuck instead?

```
\[9:47:06 PM\]  Loading: 0 packages loaded
\[9:47:07 PM\]  Loading: 245 packages loaded
\[9:47:07 PM\]      currently loading: geometry ... (44 packages)
\[9:47:10 PM\]  Loading: 289 packages loaded
\[9:47:10 PM\]  Analyzing: 11520 targets (291 packages loaded, 0 targets configured)
\[9:47:11 PM\]  Analyzing: 11520 targets (306 packages loaded, 3693 targets configured)
\[9:47:12 PM\]  Analyzing: 11520 targets (396 packages loaded, 3728 targets configured)
\[9:47:14 PM\]  Analyzing: 11520 targets (439 packages loaded, 3845 targets configured)
\[9:47:15 PM\]  Analyzing: 11520 targets (480 packages loaded, 4351 targets configured)
\[9:47:16 PM\]  Analyzing: 11520 targets (486 packages loaded, 11386 targets configured)
\[9:47:16 PM\]  Analyzing: 11520 targets (490 packages loaded, 19602 targets configured)
\[9:47:18 PM\]  Analyzing: 11520 targets (497 packages loaded, 23435 targets configured)
\[9:47:19 PM\]  Analyzing: 11520 targets (502 packages loaded, 23598 targets configured)
\[9:47:20 PM\]  Analyzing: 11520 targets (505 packages loaded, 23921 targets configured)
\[9:47:21 PM\]  Analyzing: 11520 targets (509 packages loaded, 29739 targets configured)
\[9:47:22 PM\]  Analyzing: 11520 targets (511 packages loaded, 30080 targets configured)
\[9:47:24 PM\]  Analyzing: 11520 targets (513 packages loaded, 31491 targets configured)
```

That was over ten minutes ago... doesn't seem like this was the full fix.

**Comment by BetsyMcPhail** [comment]
The changes to `install_prereqs` have been applied provisioned Linux images: **drake-linux-jammy-2023-10-05** and **drake-linux-focal-2023-10-05**.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/245)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

**Pull request merged**
