### PR TITLE
Remove remaining references to "catalina"

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
When removing support for Catalina, a few instances were missed in the CI scripts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/133)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@svenevs for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/133#-:-MvKrgz-5VhGXkrS0kBe:b-m8sb1l)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
I was not able to find any other references.  Provided CI builds with apple involved were run on this branch :lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/133#-:-MvLQrtb2hIvNOCgNjbv:b-qblf5a)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @svenevs)

**Review by svenevs — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/133#-:-MvLRCY302CSrPacO4M8:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
Mac experimental build is started here --> https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur/job/mac-big-sur-clang-bazel-experimental-release/77/

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/133#-:-MvM2dH0710_fp9HH7P9:b-203pmm)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
Experimental build passed

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/133#-:-MvM8psV530YnHmAXOeR:b-rr8naj)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @BetsyMcPhail)

**Pull request merged**
