### PR TITLE
Add APPLE_ARM64 boolean, enable macOS arm64 packaging uploads

### PR DESCRIPTION
**Pull request by svenevs**
- Fixes https://github.com/RobotLocomotion/drake/issues/17909
- Saves `/usr/bin/arch` to `APPLE_ARCHITECTURE` variable and sets `APPLE_ARM64` to either `ON` or `OFF` depending on if `arm64`.
- Update packaging logic to enable S3 uploads of snopt-mosek-packaging for macOS arm64 builds.
- [X] Build parameterized with this PR: https://drake-jenkins.csail.mit.edu/view/Mac%20M1/job/mac-m1-monterey-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/2/console
    - Uploaded https://drake-packages.csail.mit.edu/drake/experimental/drake-20220913171250-171edc8494167f180d3977d62368dbe062362b0c-mac-arm64.tar.gz and https://drake-packages.csail.mit.edu/drake/experimental/drake-20220913171250-171edc8494167f180d3977d62368dbe062362b0c-mac-arm64.tar.gz.sha512 to s3.
    - I extracted it on an m1 mac and can at least `import pydrake.all` without issue.  `otool -L libdrake.so` also includes mosek (and the mosek library is installed in `lib/`).  However, it is not clear if this is sufficient testing.
- [X] Confirmatory build that x86_64 big sur still uploads: https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/14/
    - Uploaded https://drake-packages.csail.mit.edu/drake/experimental/drake-20220913185551-3b37f85adbe0ffdaa4239c2168d96888b9849e7f-mac.tar.gz and https://drake-packages.csail.mit.edu/drake/experimental/drake-20220913185551-3b37f85adbe0ffdaa4239c2168d96888b9849e7f-mac.tar.gz.sha512
- [X] Confirmatory build that x86_64 monterey does *not* upload: https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-monterey-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/6/
    - Did not upload anything to s3.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/181)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
-blocked +@BetsyMcPhail for review please.  These changes only affect mac, the long term consequence of this change is we are committing to `drake-latest-mac-arm64.tar.gz` (adding `-arm64`, which could be something else like `-m1`).  I believe we prefer `arm64` everywhere else except jenkins naming schemes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/181#-:-NBtAAKSD4kU35h-_ZBT:b-th2r2i)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — DISMISSED** [review]
I don't have a strong opinion on `-arm64` vs `-m1`. :lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/181#-:-NBx8-v48vEb-1-wQ0zR:b-76evn6)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`driver/environment.cmake` line 220 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/181#-NBx61wo21Caee3mYIPn:-NBx61wo21Caee3mYIPo:bsp0t5o) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/3f9f33264215a705dd2a56f34a9881b2da5515e1/driver/environment.cmake#L220)):*
> ```CMake
> if(REGEX_MATCH_RESULT)
>   if(APPLE)
>     if(NOT APPLE_ARM64)
> ```

Nit Switch to `if(APPLE_ARM64)` here to match order of other comparisons in this PR.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/181)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

___
*[`driver/environment.cmake` line 220 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/181#-NBx61wo21Caee3mYIPn:-NBxCcZz04BZbmQjir5j:bxbs3ca) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/3f9f33264215a705dd2a56f34a9881b2da5515e1/driver/environment.cmake#L220)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit Switch to `if(APPLE_ARM64)` here to match order of other comparisons in this PR.  
</blockquote></details>

OK, good call -- I switched things around to match the others :+1:

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/181#-:-NCRbOq22EwWzRs03Cs-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

**Comment by svenevs** [comment]
We are keeping `mac-arm64` at least for now [as discussed on slack](https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1663179510237599).

**Pull request merged**
