### PR TITLE
Enable OpenMP in CMake "everything" builds

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add OpenMP to the list of things that can be turned on or off, and is turned on by "everything". Teach the CMake front-end driver to understand the OpenMP toggle.

Note that, at present, only the "everything" builds enable OpenMP, and the Bazel front-end handles "everything" differently, and so does not need to be modified at this time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/260)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Test builds:

https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-focal-gcc-cmake-experimental-everything-release/6/
https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-jammy-gcc-cmake-experimental-everything-release/4/
https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-focal-unprovisioned-gcc-cmake-experimental-everything-debug/12/
https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-jammy-unprovisioned-gcc-cmake-experimental-everything-debug/12/

**Comment by mwoehlke-kitware** [comment]
+@BetsyMcPhail for review, please

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for review please!

\CC @svenevs

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/260)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Pull request merged**
