### PR TITLE
Revert "[orka] Enable mac-x86-beta (#204)"

### PR DESCRIPTION
**Pull request by svenevs**
This reverts commit 28a0cfb342729fcad9198c467334170b6538151b.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`ctest_driver_script_wrapper.bash` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271#-NtWTqEHALRnaoIJPV3Q:-NtWTqEHALRnaoIJPV3R:b-wglpdt) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/ec5b9b53969bdccffb6e8b90881296a2fa2fba8d/ctest_driver_script_wrapper.bash#L64)):*
> ```Shell
>     chronyc tracking
> elif [ "$(uname)" == "Darwin" ]; then
>     : # Allow macOS to proceed without explicit synchronization.
> ```

working, will launch two mac jobs, we want to make sure they get past launching and actually start building

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`ctest_driver_script_wrapper.bash` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271#-NtWTqEHALRnaoIJPV3Q:-NtWUKLNAorHkzJxof2h:b-f1xlz4) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/ec5b9b53969bdccffb6e8b90881296a2fa2fba8d/ctest_driver_script_wrapper.bash#L64)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, will launch two mac jobs, we want to make sure they get past launching and actually start building
</blockquote></details>

- arm: https://drake-jenkins.csail.mit.edu/view/Mac%20ARM/job/mac-arm-ventura-clang-bazel-experimental-release/5244/
- x86: https://drake-jenkins.csail.mit.edu/view/Mac%20Monterey%20Unprovisioned/job/mac-x86-monterey-unprovisioned-clang-wheel-experimental-release/64/

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`ctest_driver_script_wrapper.bash` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271#-NtWTqEHALRnaoIJPV3Q:-NtWUg0q9Y0gIoPTR6ED:b-xdm928) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/ec5b9b53969bdccffb6e8b90881296a2fa2fba8d/ctest_driver_script_wrapper.bash#L64)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

- arm: https://drake-jenkins.csail.mit.edu/view/Mac%20ARM/job/mac-arm-ventura-clang-bazel-experimental-release/5244/
- x86: https://drake-jenkins.csail.mit.edu/view/Mac%20Monterey%20Unprovisioned/job/mac-x86-monterey-unprovisioned-clang-wheel-experimental-release/64/
</blockquote></details>

Arm job looked good:

```
[10:50:36 AM]  + [[ mac-arm-ventura-clang-bazel-experimental-release =~ unprovisioned ]]
[10:50:36 AM]  ++ type -P chronyc
[10:50:36 AM]  + '[' -n '' ']'
[10:50:36 AM]  ++ uname
[10:50:36 AM]  + '[' Darwin == Darwin ']'
[10:50:36 AM]  + :
[10:50:36 AM]  + AGENT=ssh-agent
[10:50:36 AM]  + [[ **** == \- ]]
[10:50:36 AM]  + ssh-agent ctest --extra-verbose --no-compress-output --script /Users/admin/workspace/mac-arm-ventura-clang-bazel-experimental-release/ci/ctest_driver_script.cmake
[10:50:36 AM]  * Extra verbosity turned on
[10:50:36 AM]  Reading Script: /Users/admin/workspace/mac-arm-ventura-clang-bazel-experimental-release/ci/ctest_driver_script.cmake
[10:50:36 AM]  -- Executing user environment provisioning script...
[10:50:36 AM]  2024/03/21 10:50:36 Downloading https://releases.bazel.build/7.0.2/release/bazel-7.0.2-darwin-arm64...
[10:50:37 AM]  Extracting Bazel installation...
[10:50:38 AM]  Starting local Bazel server and connecting to it...
[10:50:40 AM]  *** Build Description: <a title="cd404aa18660392ecd36bd15baf86753f67d8860" href="https://github.com/RobotLocomotion/drake/commit/cd404aa18660392ecd36bd15baf86753f67d8860">cd404aa</a>
[10:50:44 AM]  ampl-mp 3.1.0_3
```

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail fore review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271#-:-NtWVsiiEBJNyz13or0a:b-vqrtvr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

___
*[`ctest_driver_script_wrapper.bash` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271#-NtWTqEHALRnaoIJPV3Q:-NtWVe7b5npLPnpjOOXi:bhwjgyp) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/ec5b9b53969bdccffb6e8b90881296a2fa2fba8d/ctest_driver_script_wrapper.bash#L64)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Arm job looked good:

```
[10:50:36 AM]  + [[ mac-arm-ventura-clang-bazel-experimental-release =~ unprovisioned ]]
[10:50:36 AM]  ++ type -P chronyc
[10:50:36 AM]  + '[' -n '' ']'
[10:50:36 AM]  ++ uname
[10:50:36 AM]  + '[' Darwin == Darwin ']'
[10:50:36 AM]  + :
[10:50:36 AM]  + AGENT=ssh-agent
[10:50:36 AM]  + [[ **** == \- ]]
[10:50:36 AM]  + ssh-agent ctest --extra-verbose --no-compress-output --script /Users/admin/workspace/mac-arm-ventura-clang-bazel-experimental-release/ci/ctest_driver_script.cmake
[10:50:36 AM]  * Extra verbosity turned on
[10:50:36 AM]  Reading Script: /Users/admin/workspace/mac-arm-ventura-clang-bazel-experimental-release/ci/ctest_driver_script.cmake
[10:50:36 AM]  -- Executing user environment provisioning script...
[10:50:36 AM]  2024/03/21 10:50:36 Downloading https://releases.bazel.build/7.0.2/release/bazel-7.0.2-darwin-arm64...
[10:50:37 AM]  Extracting Bazel installation...
[10:50:38 AM]  Starting local Bazel server and connecting to it...
[10:50:40 AM]  *** Build Description: <a title="cd404aa18660392ecd36bd15baf86753f67d8860" href="https://github.com/RobotLocomotion/drake/commit/cd404aa18660392ecd36bd15baf86753f67d8860">cd404aa</a>
[10:50:44 AM]  ampl-mp 3.1.0_3
```
</blockquote></details>

done, x86 job works too

```
[10:54:41 AM]  ++ type -P chronyc
[10:54:41 AM]  + '[' -n '' ']'
[10:54:41 AM]  ++ uname
[10:54:41 AM]  + '[' Darwin == Darwin ']'
[10:54:41 AM]  + :
[10:54:41 AM]  + AGENT=ssh-agent
[10:54:41 AM]  + [[ **** == \- ]]
[10:54:41 AM]  + ssh-agent ctest --extra-verbose --no-compress-output --script /Users/monterey/workspace/mac-x86-monterey-unprovisioned-clang-wheel-experimental-release/ci/ctest_driver_script.cmake
[10:54:41 AM]  * Extra verbosity turned on
[10:54:41 AM]  Reading Script: /Users/monterey/workspace/mac-x86-monterey-unprovisioned-clang-wheel-experimental-release/ci/ctest_driver_script.cmake
```

FWIW it's because both vSphere and orka m1 are hosted on the east coast (atlanta).  So time sync isn't needed, because that's where jenkins is too.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/271)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @svenevs)

**Pull request merged**
