### PR TITLE
Add "git" to wheel local version label

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Change the wheel's local version label from `<SHA>` to `git<SHA>`. This appears to be required to preserve possible leading zeros in the SHA, as otherwise it appears that something in the bowels of Python's wheel building treats the local version label as a number (and strips leading zeroes) rather than always treating it as a string.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/155)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Test build: https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/17/

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: pending CI build

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/155#-:-N1PFRI38ocqOV0Z2YtL:b-p8wm44)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
The CI run passed:
```
...
[10:14:58 AM]  #24 61.99 Fixed-up wheel written to /wheel/wheelhouse/drake-0.0.2022.5.6.16.41.38+git08240641-cp39-cp39-manylinux_2_31_x86_64.whl
...
```

**Review by jwnimmer-tri — APPROVED** [review]

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/155#-:-N1PYh_90ySL4ujK7snD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Pull request merged**
