### PR TITLE
Add Noble support to CI

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves https://github.com/RobotLocomotion/drake/issues/20835

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
`awscli` has been installed on the Noble image following the instructions here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. The internal Continuous Integration document has been updated to include this process.

Experimental jobs using this PR:
https://drake-jenkins.csail.mit.edu/view/Linux%20Noble%20Unprovisioned/job/linux-noble-unprovisioned-gcc-bazel-experimental-release/
https://drake-jenkins.csail.mit.edu/view/Linux%20Jammy%20Unprovisioned/job/linux-jammy-unprovisioned-clang-bazel-experimental-release/37/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286#-:-Nwyjiq29E8czFKpoLAb:b-ipk0ux)* status: 0 of 2 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
Updated jobs (previous failures are unrelated to this PR):
https://drake-jenkins.csail.mit.edu/view/Linux%20Jammy%20Unprovisioned/job/linux-jammy-unprovisioned-gcc-bazel-experimental-release/48/
https://drake-jenkins.csail.mit.edu/job/linux-noble-unprovisioned-gcc-bazel-experimental-release/7/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286#-:-NwzBAKu-ipdzCS5dzs3:bxca8s5)* status: 0 of 2 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286#-:-NwzBQub4-x7t3amKIvR:bnyvoyh)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
What's wrong with `awscli` from apt?

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286#-:-NwzNMv87n-ap7eldeFl:b-e8euif)* status: 1 of 2 files reviewed, all discussions resolved

**Comment by BetsyMcPhail** [comment]
It doesn't exist for Noble (yet?)

**Comment by mwoehlke-kitware** [comment]
Okay. Maybe that warrants a comment to revisit?

**Review by mwoehlke-kitware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286#-:-NwzP8ghDnwySKO9qWJ5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
TODO comment added

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286#-:-NwzPtbD8d6b3mBFd7u5:b-tl69w6)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/286)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Pull request merged**
