### PR TITLE
Simplify logic that determines which jobs use the cache

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
* Unless specifically excluded, all jobs read from the cache. Exceptions include Mac x86, Unprovisioned, Coverage, and Health Check ~~and Weekly~~ jobs.

* Continous jobs that read from the cache also write to the cache.

All of the code that determines the caching behavior has been moved to one place.

Resolves https://github.com/RobotLocomotion/drake/issues/19341

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231#-:-NYyHFzb7312osh0qIqJ:bnyvoyh)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231#-NYyHOP3DV57ym_uqvLu:-NYyHOP3DV57ym_uqvLv:b-wbqt86) (no related file):*
> Unless specifically excluded, all jobs read from the cache. Exceptions include ... Weekly jobs.

I'm not sure where this came from.  I don't immediately see a reason why Weekly should be excluded from reading the cache?

___

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231#-NYyHOP3DV57ym_uqvLu:-NYyHiuy36Nh0777H63x:b-me7dj0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Unless specifically excluded, all jobs read from the cache. Exceptions include ... Weekly jobs.

I'm not sure where this came from.  I don't immediately see a reason why Weekly should be excluded from reading the cache?
</blockquote></details>

I was about to ask you about weekly jobs, you beat me to it. Weekly jobs don't have any overlap with Continuous, they are MOSEK, Gurobi, SNOPT or coverage (excluded anyway). On the other hand, reading the cache should, in theory, not affect anything else. From your question, I'm guessing you'd prefer to include them and adjust later if they cause issues?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231#-NYyHOP3DV57ym_uqvLu:-NYyJklz9MmQ4JRfsPm2:b-a89x1m) (no related file):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I was about to ask you about weekly jobs, you beat me to it. Weekly jobs don't have any overlap with Continuous, they are MOSEK, Gurobi, SNOPT or coverage (excluded anyway). On the other hand, reading the cache should, in theory, not affect anything else. From your question, I'm guessing you'd prefer to include them and adjust later if they cause issues?
</blockquote></details>

Yes, having them _read_ from the cache should be harmless.  In fact, they will probably end up sharing cache hits with other jobs e.g. building `lcm` or `common` or etc stuff.  It's the same as the nightlies that don't match up with any continuous.

___

**Comment by BetsyMcPhail** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, having them _read_ from the cache should be harmless.  In fact, they will probably end up sharing cache hits with other jobs e.g. building `lcm` or `common` or etc stuff.  It's the same as the nightlies that don't match up with any continuous.
</blockquote></details>

Works for me. I will update the PR.

**Review by mwoehlke-kitware — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231)* status: all files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/231#-NYyHOP3DV57ym_uqvLu:-NZ7XROi-n4Mx1bM36FH:bnfp4nl) (no related file):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Works for me. I will update the PR.
</blockquote></details>

:lgtm:

___

**Pull request merged**
