### PR TITLE
Add staging job for wheels

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add the idea of a new 'staging' track, specifically intended to be used for jobs whose purpose is to build a release candidate. Tweak wheel build to recognize such jobs and accept a version from the environment (i.e. to be supplied as a parameter to the job) rather than using a time-stamped version.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/173)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Test build at https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur%20Unprovisioned/job/mac-big-sur-unprovisioned-clang-wheel-staging-snopt-mosek-release/13/console. Seems to be working (I was able to download the wheel from AWS).

**Review by svenevs — CHANGES_REQUESTED** [review]
+@svenevs 

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-:-N7IO5C1AxM8kOU2tKaO:b-yk6sjg)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware and @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-N7IPWtzEK8_kBYozb95:-N7IPWtzEK8_kBYozb96:b-wry4d0) (no related file):*
It uploads to https://drake-packages.csail.mit.edu/drake/experimental/drake-1.6a2-cp39-cp39-macosx_11_0_x86_64.whl on the `experimental` track for s3.  We want these to be going to `staging` right?

https://github.com/RobotLocomotion/drake-ci/blob/280db0004c08b8d9c068a1d456f3e05020a476bb/driver/functions.cmake#L322

Something to detect `staging` in the job name and change the `--track` parameter instead of using `DASHBOARD_TRACK`?

Or alternatively this (and any other future builds) need to have their `DASHBOARD_TRACK` changed (somewhere...)?

___

**Comment by svenevs** [comment]
Next job link: https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur%20Unprovisioned/job/mac-big-sur-unprovisioned-clang-wheel-staging-snopt-mosek-release/14/console

**Comment by mwoehlke-kitware** [comment]
Updated test build: https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur%20Unprovisioned/job/mac-big-sur-unprovisioned-clang-wheel-staging-snopt-mosek-release/16/console.

**Review by svenevs — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/173)* status: all files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-N7IPWtzEK8_kBYozb95:-N7Mx8pw1kA3EjPqWE_R:b-4wug7p) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

It uploads to https://drake-packages.csail.mit.edu/drake/experimental/drake-1.6a2-cp39-cp39-macosx_11_0_x86_64.whl on the `experimental` track for s3.  We want these to be going to `staging` right?

https://github.com/RobotLocomotion/drake-ci/blob/280db0004c08b8d9c068a1d456f3e05020a476bb/driver/functions.cmake#L322

Something to detect `staging` in the job name and change the `--track` parameter instead of using `DASHBOARD_TRACK`?

Or alternatively this (and any other future builds) need to have their `DASHBOARD_TRACK` changed (somewhere...)?
</blockquote></details>

OK, job 16 uploaded to `staging` as expected.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-N7MxP2hDuqvAz8nvaWa:-N7MxP2hDuqvAz8nvaWb:bm0xj8n) (no related file):*
One last build, redoing a nightly to confirm `-latest` tagging to be extra safe.  I don't see why we should experience an issue

https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-nightly-snopt-mosek-release/101/console

___
___
*[`tools/upload-to-aws.py` line 173 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-N7MxL_CEX2oPYKdvPJG:-N7MxL_CEX2oPYKdvPJH:b-7y5ftj) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/551e227206f5597570b8781518e9a58d08f71cb6/tools/upload-to-aws.py#L173)):*
> ```Python
> 
>     # For nightly and continuous, upload a 'latest' artifact as well.
>     if options.nightly or options.continuous:
> ```

BTW good catch here!

**Review by svenevs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-:-N7N8ktMB7ceBGyETYkx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ci/173#-N7MxP2hDuqvAz8nvaWa:-N7N8gtd5uxwTFNWvlwd:bze3scx) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

One last build, redoing a nightly to confirm `-latest` tagging to be extra safe.  I don't see why we should experience an issue

https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-nightly-snopt-mosek-release/101/console
</blockquote></details>

OK works as expected :+1:

___

**Pull request merged**
