### PR TITLE
Bump Linux Gurobi to 9.5.2

### PR DESCRIPTION
**Pull request by williamjallen**
Progress towards https://github.com/RobotLocomotion/drake/issues/14157

Do not merge yet.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192)

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
+@BetsyMcPhail for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192#-:-NMGCyCN6VS4iPQu5kUX:b6t817a)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Comment by williamjallen** [comment]
The tests passed with these changes: https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-experimental-everything-release/4881/console

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @williamjallen)

___
*[`setup/ubuntu/install_prereqs` line 100 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192#-NMGXlXe1KwufO8Ys5Lj:-NMGXlXe1KwufO8Ys5Lk:boabed6) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/2668cfddf0ad95bdf2ac4ce1b32e443a132dbc58/setup/ubuntu/install_prereqs#L100)):*
> ```
> 
> wget -nv -t 4 -O /tmp/gurobi9.5.1_linux64.tar.gz --retry-connrefused \
>   https://packages.gurobi.com/9.5/gurobi9.5.1_linux64.tar.gz
> ```

The 9.5.1 on this and the prior line seems very suspicious.

**Comment by williamjallen** [comment]
Good catch.  I edited after committing and forgot to commit again before pushing.  I'm somewhat confused (and concerned!) about how the tests passed with that though.

I kicked off this job with the new changes: https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-experimental-everything-release/4884/console

**Comment by jwnimmer-tri** [comment]
I think that only "unprovisioned" builds run this install script.  Other builds just use the already-installed AMI.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Comment by williamjallen** [comment]
Ok, I ran an [unprovisioned job](https://drake-jenkins.csail.mit.edu/view/Linux%20Focal%20Unprovisioned/job/linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release/10/console), which passed, and appears to have correctly run the install script.

**Review by BetsyMcPhail — APPROVED** [review]
I had unprovisioned in mind and then sent William the link to a provisioned job. The actual unprovisioned job looks to be happily using Gurobi 9.5.2. Of real interest, we didn't update the license server, so that seems just fine with a patch version change. 

:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192#-:-NMJUMPLAQtcsUjjmEcc:b9zum4a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @williamjallen)

**Review by BetsyMcPhail — APPROVED** [review]
Just to make sure nothing unexpected happens, let's try a jammy-gcc job too: https://drake-jenkins.csail.mit.edu/view/Linux%20Jammy%20Unprovisioned/job/linux-jammy-unprovisioned-gcc-bazel-experimental-gurobi-debug/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192#-:-NMJWWmHEl9JvgbnFvgq:b-d6mhf9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @williamjallen)

**Review by williamjallen — COMMENTED** [review]
I just started the job mentioned above.  The results will be here: https://drake-jenkins.csail.mit.edu/view/Linux%20Jammy%20Unprovisioned/job/linux-jammy-unprovisioned-gcc-bazel-experimental-gurobi-debug/2/console

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/192#-:-NMGDNCh8GwUgA5HKi5M:bbhl8xs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @williamjallen)

**Pull request merged**
