### PR TITLE
Switch Mac packaging from Ventura to Sonoma

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21978

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/292)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-cmake-experimental-packaging/2/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/292#-:-O8DfyeW4IFumn7uCkj1:brrwnie)* status: 0 of 1 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review. Merge needs to be coordinated with https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/152 and https://github.com/RobotLocomotion/drake/pull/21984

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/292#-:-O8Hvv1D-lduYBcvM_UV:b-yhv0tx)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
Ping on this (& friends).  The release ETA is next week, so we should try to get this merged this week.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

Do you plan to remove Sonoma support later?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/292#-:-O8ci8ub-kz8qokV65dH:b-ppjuvo)* status: 0 of 1 files reviewed, all discussions resolved

**Review by mwoehlke-kitware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
I'm not sure I understand the question?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/292#-:-O8ciVEl9no9_J6MTtRf:bnpgwzr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Comment by mwoehlke-kitware** [comment]
Sorry, I meant *Ventura* support. Ventura is still mentioned in two places.

**Comment by BetsyMcPhail** [comment]
Yes, coming soon!

**Pull request merged**
