### PR TITLE
Remove support for Ventura

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21978

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/293)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
Do not merge until after https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/155

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/293#-:-O8d2HYC9h0Fhdx2UVR1:bnyvoyh)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by BetsyMcPhail — COMMENTED** [review]
drake-jenkins-jobs changes have been deployed and merged, this can be merged at any time. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/293#-:-O8w89rY8y2OJKiW9X6a:b-oqxd9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/293)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Comment by mwoehlke-kitware** [comment]
:lgtm:

**Pull request merged**
