### PR TITLE
Start moving packaging to CMake builds

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add ability for CMake builds to perform packaging steps. A major motivation for this, besides that CMake builds are the only officially supported mechanism for installs (which means we ought to have been using CMake for packages all along), is that this allows us to use the VERSION.TXT generated by the Drake build, rather than having our own logic to create it.

For now, Bazel packaging is left alone so that we can make sure the new jobs are working, but the intent is to remove them in the near future.

Requires https://github.com/RobotLocomotion/drake/pull/21146.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/277)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-jammy-unprovisioned-gcc-bazel-experimental-packaging/24/
https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging/10/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/277#-:-NudLWAM3oKQB6I4IJsz:b6j8r1l)* status: 0 of 8 files reviewed, all discussions resolved

**Review by BetsyMcPhail — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/277)* status: all files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`driver/configurations/bazel.cmake` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/277#-NudM2IKBxTk7i2tJBQl:-NudM2IKBxTk7i2tJBQm:b-jg4h47) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f1e8f53f6155a09d6c60717c37ee8f396017f5d9/driver/configurations/bazel.cmake#L44)):*
> ```CMake
> # Set bazel options
> set(DASHBOARD_BAZEL_STARTUP_OPTIONS)
> set(DASHBOARD_OUTPUT_USER_ROOT "${CTEST_BINARY_DIRECTORY}")
> ```

`DASHBOARD_OUTPUT_USER_ROOT` is still used in tools/user.bazelrc.in.

**Comment by mwoehlke-kitware** [comment]
*[`driver/configurations/bazel.cmake` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/277#-NudM2IKBxTk7i2tJBQl:-NudToh6EqustpKmoZHu:bt2vr1b) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/f1e8f53f6155a09d6c60717c37ee8f396017f5d9/driver/configurations/bazel.cmake#L44)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

`DASHBOARD_OUTPUT_USER_ROOT` is still used in tools/user.bazelrc.in.
</blockquote></details>

Fixed.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Pull request merged**
