### PR TITLE
bazel 5, macOS: use --config=apple_debug not --compilation_mode=debug

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/135)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for review please (after launching jobs).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/135#-:-MvPCwU1384YR5yMYfCu:bwem770)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur/job/mac-big-sur-clang-bazel-experimental-debug/15/
https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur/job/mac-big-sur-clang-bazel-experimental-everything-debug/7/

:lgtm: pending CI results

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/135#-:-MvPFaJx-72vhh1IdZ9Y:b-a7owvh)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
Ugh, I didn't think about the downside -- the dSYM files are probably large.  One of the builds failed with "no space left", the other is still running, but I'd wager it will also fail.

I suppose we should abandon the `--config` change now, and instead add `build --notrim_test_configuration` directly to `drake/tools/macos.bazelrc`.

**Comment by svenevs** [comment]
"Fixed" in https://github.com/RobotLocomotion/drake/pull/16546.

**Pull request closed without merging**
