### PR TITLE
Reporting tweaks

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Twiddle a bit with how we report our configuration in preparation for the catkin refactor. This moves the reporting to a separate step file, and arranges to omit some items from the report that are not relevant to the configuration (e.g. non-ROS builds will no longer show the ROS environment, which is always empty, non-tooled builds will no longer show several tooling variables which are always empty...).

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
I tested this locally with `ENV{memcheck}=tsan`; as expected, ROS and irrelevant tooling stuff was elided, while `CTEST_MEMORYCHECK_TYPE` was present. Given that this affects only reporting, additional runs are not likely to add information short of running every possible permutation of tooling.

**Comment by mwoehlke-kitware** [comment]
...and since I've now added some changes to how the URL's are produced: [linux-clang-ninja-experimental](https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-experimental/35) test buid.

**Comment by jamiesnape** [comment]
No CDash link to the drake dashboard?

**Comment by jamiesnape** [comment]
Also no build name.

**Comment by mwoehlke-kitware** [comment]
> No CDash link to the drake dashboard?

Alas, the post-build script is utterly inflexible as to what it matches to find these. Should be fixed now.

> Also no build name.

Not sure what this means?

**Comment by mwoehlke-kitware** [comment]
New [linux-clang-ninja-experimental](https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-experimental/36) test buid.

**Comment by jamiesnape** [comment]
Build Name is `(empty)` here:
https://drake-cdash.csail.mit.edu/index.php?project=drake-superbuild&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-ninja-experimental-release-35&field2=buildstarttime&compare2=84&value2=now

**Comment by mwoehlke-kitware** [comment]
> Build Name is `(empty)` [here](https://drake-cdash.csail.mit.edu/index.php?project=drake-superbuild&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-ninja-experimental-release-35&field2=buildstarttime&compare2=84&value2=now)

D'oh... darned variable scope :blush:. Should be fixed.

New [linux-clang-ninja-experimental](https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-experimental/37) test buid.

**Pull request merged**
