### PR TITLE
Enable mac-arm64 cache server

### PR DESCRIPTION
**Pull request by svenevs**
Toward https://github.com/RobotLocomotion/drake/issues/18286.

- [X] Test populate job: https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/23/consoleFull
    - Commit: https://github.com/RobotLocomotion/drake/commit/34f7442abb21485a61d26006605a54085b167cf6
    - Runtime: 1 hour 6 minutes.
    - Cache size (`du -s --bytes /cache/toyotacache/v2/a420998e5a8ba94589c8417c20e21a7513f9c5d04d473a4214256012046eb528/`): 13160869813 => 13.16 GB
- [X] Test read jobs:
    - Isolated (only VM running): https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/24/consoleFull
        - Commit: https://github.com/RobotLocomotion/drake/commit/34f7442abb21485a61d26006605a54085b167cf6
        - Runtime: 7 minutes 2 seconds :partying_face:
    - Concurrent (4 builds running):
        - Commit: https://github.com/RobotLocomotion/drake/commit/dc71ec6f402840842277122176d1627fe2de31a5
        - Runtime Average: 49 minutes 51 seconds.  Commit was a day old, not that many hits though -- but it's definitely working as expected and we will get better metrics as time (and continuous) continue.
        - Jobs: [38](https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/38/consoleFull), [39](https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/39/consoleFull), [40](https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/40/consoleFull), and [41](https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/41/consoleFull).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`driver/configurations/cache.cmake` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193#-NMaZ-ju1MNcWrZXQDj2:-NMaZ-ju1MNcWrZXQDj3:b-i57wr) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b09ec13ebbeb25e2541862bcee04767dbc189ad6/driver/configurations/cache.cmake#L70)):*
> ```CMake
>       "*** Disabling remote cache because could NOT contact remote cache server"
>       "\n${DASHBOARD_DOWNLOAD_LOG}"
>     )
> ```

Example log messaging of these changes and why they are useful:

```
[8:24:16 PM]  -- Testing download of remote cache server: 'http://10.221.188.4:6060'
[8:24:16 PM]  CMake Warning at /Users/admin/workspace/mac-arm-monterey-clang-bazel-experimental-release/ci/driver/configurations/cache.cmake:67 (message):
[8:24:16 PM]    *** Disabling remote cache because could NOT contact remote cache server
[8:24:16 PM]  
[8:24:16 PM]      Trying 10.221.188.4:6060...
[8:24:16 PM]  
[8:24:16 PM]    Connected to 10.221.188.4 (10.221.188.4) port 6060 (#0)
[8:24:16 PM]  
[8:24:16 PM]    GET / HTTP/1.1
[8:24:16 PM]  
[8:24:16 PM]    Host: 10.221.188.4:6060
[8:24:16 PM]  
[8:24:16 PM]    User-Agent: curl/7.79.1
[8:24:16 PM]  
[8:24:16 PM]    Accept: */*
[8:24:16 PM]  
[8:24:16 PM]    
[8:24:16 PM]  
[8:24:16 PM]    Mark bundle as not supporting multiuse
[8:24:16 PM]  
[8:24:16 PM]    HTTP/1.1 403 Forbidden
[8:24:16 PM]  
[8:24:16 PM]    Server: nginx/1.18.0 (Ubuntu)
[8:24:16 PM]  
[8:24:16 PM]    Date: Wed, 25 Jan 2023 01:24:15 GMT
[8:24:16 PM]  
[8:24:16 PM]    Content-Type: text/html
[8:24:16 PM]  
[8:24:16 PM]    Content-Length: 162
[8:24:16 PM]  
[8:24:16 PM]    Connection: keep-alive
[8:24:16 PM]  
[8:24:16 PM]    The requested URL returned error: 403
[8:24:16 PM]  
[8:24:16 PM]    Closing connection 0
[8:24:16 PM]  
[8:24:16 PM]  Call Stack (most recent call first):
[8:24:16 PM]    /Users/admin/workspace/mac-arm-monterey-clang-bazel-experimental-release/ci/driver/configurations/bazel.cmake:105 (include)
[8:24:16 PM]    /Users/admin/workspace/mac-arm-monterey-clang-bazel-experimental-release/ci/ctest_driver_script.cmake:129 (include)
```

**Review by svenevs — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

___
*[`driver/configurations/cache.cmake` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193#-NMaZ-ju1MNcWrZXQDj2:-NMe_RwYDxpEPMD9CDmt:bbg7yqo) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b09ec13ebbeb25e2541862bcee04767dbc189ad6/driver/configurations/cache.cmake#L70)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Example log messaging of these changes and why they are useful:

```
[8:24:16 PM]  -- Testing download of remote cache server: 'http://10.221.188.4:6060'
[8:24:16 PM]  CMake Warning at /Users/admin/workspace/mac-arm-monterey-clang-bazel-experimental-release/ci/driver/configurations/cache.cmake:67 (message):
[8:24:16 PM]    *** Disabling remote cache because could NOT contact remote cache server
[8:24:16 PM]  
[8:24:16 PM]      Trying 10.221.188.4:6060...
[8:24:16 PM]  
[8:24:16 PM]    Connected to 10.221.188.4 (10.221.188.4) port 6060 (#0)
[8:24:16 PM]  
[8:24:16 PM]    GET / HTTP/1.1
[8:24:16 PM]  
[8:24:16 PM]    Host: 10.221.188.4:6060
[8:24:16 PM]  
[8:24:16 PM]    User-Agent: curl/7.79.1
[8:24:16 PM]  
[8:24:16 PM]    Accept: */*
[8:24:16 PM]  
[8:24:16 PM]    
[8:24:16 PM]  
[8:24:16 PM]    Mark bundle as not supporting multiuse
[8:24:16 PM]  
[8:24:16 PM]    HTTP/1.1 403 Forbidden
[8:24:16 PM]  
[8:24:16 PM]    Server: nginx/1.18.0 (Ubuntu)
[8:24:16 PM]  
[8:24:16 PM]    Date: Wed, 25 Jan 2023 01:24:15 GMT
[8:24:16 PM]  
[8:24:16 PM]    Content-Type: text/html
[8:24:16 PM]  
[8:24:16 PM]    Content-Length: 162
[8:24:16 PM]  
[8:24:16 PM]    Connection: keep-alive
[8:24:16 PM]  
[8:24:16 PM]    The requested URL returned error: 403
[8:24:16 PM]  
[8:24:16 PM]    Closing connection 0
[8:24:16 PM]  
[8:24:16 PM]  Call Stack (most recent call first):
[8:24:16 PM]    /Users/admin/workspace/mac-arm-monterey-clang-bazel-experimental-release/ci/driver/configurations/bazel.cmake:105 (include)
[8:24:16 PM]    /Users/admin/workspace/mac-arm-monterey-clang-bazel-experimental-release/ci/ctest_driver_script.cmake:129 (include)
```
</blockquote></details>

Done, in the event that cmake cannot contact the cache server including its error messages is extra helpful to log.  In this example, bad nginx configurations leading to a 403 at `GET /`.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

___
*[`driver/environment.cmake` line 172 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193#-NMe_sxI6wavoGJ1KaJM:-NMe_sxI6wavoGJ1KaJN:b-wxdiye) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/d63046980e91620147d7a66f3cfdabb361aef297/driver/environment.cmake#L172)):*
> ```CMake
> # This expression is a temporary kludge to test out the cache with mac-arm using
> # the same jobs that mac-x86 is currently caching.
> string(REGEX MATCH "(mac-arm-monterey-clang-bazel-continuous-release|mac-arm-monterey-clang-bazel-experimental-everything-release|mac-arm-monterey-clang-bazel-experimental-release|mac-arm-monterey-clang-bazel-nightly-everything-release|mac-arm-monterey-clang-cmake-experimental-everything-release|mac-arm-monterey-clang-cmake-experimental-release|mac-arm-monterey-clang-cmake-nightly-everything-release|mac-arm-monterey-clang-cmake-nightly-release)" REGEX_MATCH_RESULT "${DASHBOARD_JOB_NAME}")
> ```

FYI though not pretty this lets us get things in to test ASAP, and also makes it easy to pull this back out (not a revert PR, just this section and the part below bypassing the existing logic).

**Review by svenevs — COMMENTED** [review]
+@mwoehlke-kitware for review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193#-:-NMejueAEwohXEYCW7AF:bwq5xyt)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
:lgtm: I guess...

**Review by svenevs — COMMENTED** [review]
:lgtm: not clear what reviewable is blocked on...

https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/45/console

I confirmed with the latest changes here drake-ci still runs as expected.  All were cache misses because the cache was populated before the orka image upgrade.  Nightlies tonight should give us a good sampling!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/193#-:-NMenSaRAk6aIJ8HWH2O:ba9d791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by williamjallen — APPROVED** [review]
Approving to enable merging.

**Pull request merged**
