### PR TITLE
Add 'EVERYTHING' option for Bazel CI

### PR DESCRIPTION
**Pull request by BetsyMcPhail**

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
I am creating an experimental 'linux-clang-bazel-experimental-everything' job to test this.

**Comment by BetsyMcPhail** [comment]
https://drake-jenkins.csail.mit.edu/view/Bazel/job/linux-clang-bazel-experimental-everything/2/console

Two errors:
1. `16:11:50 WARNING: /home/ubuntu/workspace/linux-clang-bazel-experimental-everything/_bazel_ubuntu/8d391cf6446e7db88e434ba525991e35/external/gurobi/BUILD:6:1: gurobi.bzl: The saved value of GUROBI_PATH is empty or unset; export GUROBI_PATH to the correct value and then do 'bazel clean'..`

2. `16:11:51 error cloning snopt:
16:11:51 + cd /home/ubuntu/workspace/linux-clang-bazel-experimental-everything/_bazel_ubuntu/8d391cf6446e7db88e434ba525991e35/external
16:11:51 + rm -rf /home/ubuntu/workspace/linux-clang-bazel-experimental-everything/_bazel_ubuntu/8d391cf6446e7db88e434ba525991e35/external/snopt
16:11:51 + git clone git@github.com:RobotLocomotion/snopt.git /home/ubuntu/workspace/linux-clang-bazel-experimental-everything/_bazel_ubuntu/8d391cf6446e7db88e434ba525991e35/external/snopt
16:11:51 Cloning into '/home/ubuntu/workspace/linux-clang-bazel-experimental-everything/_bazel_ubuntu/8d391cf6446e7db88e434ba525991e35/external/snopt'...
16:11:51 Permission denied (publickey).
16:11:51 fatal: Could not read from remote repository.
16:11:51 
16:11:51 Please make sure you have the correct access rights
16:11:51 and the repository exists.
16:11:51  and referenced by '//drake/solvers:snopt_solver'.`

**Comment by david-german-tri** [comment]
Cool, both of those make sense:

1. We need to set the GUROBI_PATH environment variable, along the same lines as GUROBI_DISTRO [here](https://github.com/RobotLocomotion/drake-ci/blob/fc78ada675d4edcbf26387bb6d3c643312200e03/driver/configurations/packages.cmake#L103). With the tweak that the `.tar.gz` should be unzipped, and the environment variable value should be the path to `gurobi605/linux64`. 

2. The AMI needs to have an SSH key that will let it access RobotLocomotion/snopt.  The existing CMake builders that use SNOPT must have that set up somehow.

**Comment by BetsyMcPhail** [comment]
Making progress, new set of errors here: https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=380358

**Comment by david-german-tri** [comment]
Those are legit bugs!  PR coming soon.  @siyuanfeng-tri FYI

The CDash+Bazel improvements remain great, BTW.

**Comment by siyuanfeng-tri** [comment]
i suspect CI should crash and burn given this is done correctly. 
https://github.com/RobotLocomotion/drake/blob/master/drake/examples/QPInverseDynamicsForHumanoids/BUILD#L108
this is pointing to a file that doesn't exist in master anymore.

**Comment by BetsyMcPhail** [comment]
PTAL @jamiesnape

**Comment by jamiesnape** [comment]
LGTM.

**Pull request merged**
