### PR TITLE
Publish to S3 mirror again

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Missed in https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/90.

+@svenevs for review, please.
\CC @BetsyMcPhail FYI

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/256)

### CODE REVIEW

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/256#-:-NkGENt7-P_lpxxH4p3Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @svenevs)

**Comment by jwnimmer-tri** [comment]
I am OK if you want to merge this now.

**Review by svenevs — APPROVED** [review]
:LGTM:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/256#-:-NkGNxjn3-owSBkxjIXl:bmxilld)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I confirmed it uploaded the new stuff:
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-unprovisioned-gcc-bazel-continuous-mirror-to-s3/159/consoleFull

**Pull request merged**
