### PR TITLE
When both MEMCHECK and EVERYTHING are set, merge them

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes RobotLocomotion/drake#7176.

I don't know where `run_local.bash` went, so I'm not 100% clear on how to test this locally.  In any case, we need to test it in Jenkins anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/83)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.  Also, if you could please help me test in Jenkins that would be great -- I haven't yet figured out how to fire off CI for `drake-ci` changes.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-ci/83#-:-Kvh-qPNiiuoPqrbUBK3:bnhbnkw)*

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Sanitizer/job/linux-xenial-clang-bazel-experimental-memcheck-tsan-everything/9/console

**Comment by jamiesnape** [comment]
The PR is good, but it is going to cause a lot of failures due to `FATAL: ThreadSanitizer: unexpected memory mapping` with the version of Clang that we use.

**Comment by jwnimmer-tri** [comment]
You're saying that there are further incompatibilities between `--config everything` and `--config foosan` besides the one I patched around in RobotLocomotion/drake#7193?

Assuming yes, would it make sense if I iterate locally using 16.04 and PR those fixes or nerfs to Drake master, then circle back and re-test & merge this PR?  Or are some configs so entirely broken that we should move them out of  `_ Production` CI, until they are repaired?

**Comment by jamiesnape** [comment]
> You're saying that there are further incompatibilities between --config everything and --config foosan besides the one I patched around in RobotLocomotion/drake#7193?

Looks like it for TSan, judging from the first 20 minutes or so of the build I started on CI. Probably we will need to move that one out of production.

**Comment by jwnimmer-tri** [comment]
Thanks for looking and testing.  I will circle back tomorrow and check in with the CI results, and for any updates here.

**Comment by jwnimmer-tri** [comment]
The UBSan problem is actually a bug in Drake.  I'll PR that fixup soon.

**Comment by jamiesnape** [comment]
* https://drake-jenkins.csail.mit.edu/view/Sanitizer/job/linux-xenial-clang-bazel-experimental-memcheck-tsan-everything/10/console

**Comment by jamiesnape** [comment]
Just the `run_quadrotor_dynamics_test` failiure in UBSan (https://github.com/RobotLocomotion/drake/issues/6908). FYI @naveenoid.

**Pull request merged**
