### PR TITLE
Upgrade Gurobi to 10.0.2

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/18352

Need to coordinate merging this PR with Drake PR and updating CI instances.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/237)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
With drake master (Gurobi 9.5): https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/35/

With drake updated to Gurobi 10: https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/34/

**Review by BetsyMcPhail — COMMENTED** [review]
+@svenevs for review please. I don't think we need to do any cleanup in these scripts, they are meant to be run on single use Unprovisioned images. We can remove the oldest version of Gurobi on the provisioned images by hand.  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/237#-:-Nas9TcPAIOT2QOfp87D:b-m3wpi8)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @svenevs)

**Review by svenevs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/237)* status: all files reviewed, 1 unresolved discussion (waiting on @svenevs)

___
*[`setup/ubuntu/install_prereqs` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/237#-NavMHvt2bTgEjHBYXsZ:-NavMHvt2bTgEjHBYXs_:b1uafsu) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/d1aff9672ba2fed75486c6a4cef67a5f636f3483/setup/ubuntu/install_prereqs#L121)):*
> ```
> 
> # To simplify the Gurobi upgrade process, two versions of Gurobi are installed.
> # Logic inside of drake itself determines which version will be used.
> ```

working, macOS presents possible issues, blocking to prevent merge but likely we will just keep linux dual provisioned even if it is an issue on macOS

**Comment by BetsyMcPhail** [comment]
Experimental job with both drake and drake-ci PRs: https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/36/

**Comment by svenevs** [comment]
New macOS jobs:

- https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-monterey-unprovisioned-clang-cmake-experimental-everything-release/5/
- https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-x86-monterey-unprovisioned-clang-cmake-experimental-everything-release/3/

[Linux job is faililng](https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/36/):

```
[12:56:03 PM]  FAIL: //multibody/inverse_kinematics:global_inverse_kinematics_reachable_test (see /media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/_bazel_ubuntu/09d8fb4aa2bfa1ec5105ef9619ae06d0/execroot/drake/bazel-out/k8-opt/testlogs/multibody/inverse_kinematics/global_inverse_kinematics_reachable_test/test.log)
[12:56:03 PM]  [41,592 / 41,594] 6859 / 6860 tests, 1 failed; Testing //multibody/inverse_kinematics:global_inverse_kinematics_reachable_test; 169s local ... (2 actions running)
[12:56:03 PM]  INFO: From Testing //multibody/inverse_kinematics:global_inverse_kinematics_reachable_test:
[12:56:03 PM]  ==================== Test output for //multibody/inverse_kinematics:global_inverse_kinematics_reachable_test:
[12:56:03 PM]  Using drake_cc_googletest_main.cc
[12:56:03 PM]  
[12:56:03 PM]  [==========] Running 1 test from 1 test suite.
[12:56:03 PM]  [----------] Global test environment set-up.
[12:56:03 PM]  [----------] 1 test from KukaTest
[12:56:03 PM]  [ RUN      ] KukaTest.ReachableTest
[12:56:03 PM]  Set parameter ServerPassword
[12:56:03 PM]  Set parameter TokenServer to value "172.31.29.246"
[12:56:03 PM]  Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
[12:56:03 PM]  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc:87: Failure
[12:56:03 PM]  Value of: CompareMatrices(body_pose_fk.rotation().matrix(), body_Ri, orient_tol, MatrixCompareType::absolute)
[12:56:03 PM]    Actual: false (Values at (0, 0) exceed tolerance: -0.6221956002497744 vs. -0.3673313463971569, diff = 0.25486425385261746, tolerance = 0.25
[12:56:03 PM]  m1 =
[12:56:03 PM]  -0.6221956002497744 -0.7540076383585987  0.2105828015928925
[12:56:03 PM]   0.2622182684720993  -0.454175351064407 -0.8514495464588707
[12:56:03 PM]   0.7376409795485315 -0.4745495040376833  0.4803004825192993
[12:56:03 PM]  m2 =
[12:56:03 PM]  -0.3673313463971569 -0.8234298673287244  0.1977038419998716
[12:56:03 PM]   0.3115406840022548 -0.2977569517407221 -0.8228854880311761
[12:56:03 PM]   0.7768375762913492 -0.2835395882084257  0.4485245751136551
[12:56:03 PM]  delta=
[12:56:03 PM]   -0.2548642538526175  0.06942222897012562  0.01287895959302091
[12:56:03 PM]  -0.04932241553015543   -0.156418399323685 -0.02856405842769461
[12:56:03 PM]  -0.03919659674281772  -0.1910099158292576  0.03177590740564423)
[12:56:03 PM]  Expected: true
[12:56:03 PM]  Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
[12:56:03 PM]  Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
[12:56:03 PM]  Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
[12:56:03 PM]  [  FAILED  ] KukaTest.ReachableTest (169720 ms)
[12:56:03 PM]  [----------] 1 test from KukaTest (169720 ms total)
[12:56:03 PM]  
[12:56:03 PM]  [----------] Global test environment tear-down
[12:56:03 PM]  [==========] 1 test from 1 test suite ran. (169720 ms total)
[12:56:03 PM]  [  PASSED  ] 0 tests.
[12:56:03 PM]  [  FAILED  ] 1 test, listed below:
[12:56:03 PM]  [  FAILED  ] KukaTest.ReachableTest
```

**Comment by jwnimmer-tri** [comment]
> We want to create unprovisioned versions ...

Sure, that sounds fine.

I don't recall why we have existing _cmake unprovisioned_ flavors of those two.  Possibly switching those two from cmake => bazel would be the smart move.

**Review by svenevs — APPROVED** [review]
:lgtm: I will merge this when we are ready to do all components together.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/237#-:-Nc3LC9D61xBs-Qpxu9w:bj8rba8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

___
*[`setup/ubuntu/install_prereqs` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/237#-NavMHvt2bTgEjHBYXsZ:-Nc3LANc-ILjG36P3Kxq:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/d1aff9672ba2fed75486c6a4cef67a5f636f3483/setup/ubuntu/install_prereqs#L121)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, macOS presents possible issues, blocking to prevent merge but likely we will just keep linux dual provisioned even if it is an issue on macOS
</blockquote></details>

done

**Pull request merged**
