### PR TITLE
Actually install Drake in CMake packaging builds

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add a step, used by CMake packaging builds, to actually install Drake. Install maintainer-only dependencies when doing a packaging build. Add (missing) upload steps to the CMake configuration directory. Replace "BAZEL" with "CMAKE" in the CMake flavors of the various packaging steps.

**Please *MERGE* instead of squashing.**

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-arm-jammy-unprovisioned-gcc-cmake-experimental-packaging/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-:-NuyaFie3zA0j4lm8_me:b-1xguzv)* status: 0 of 3 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
Pointer to job launched for this PR: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-arm-jammy-unprovisioned-gcc-cmake-experimental-packaging/1/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-:-NuyaMB49Uso03qadkOO:b-535otp)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by mwoehlke-kitware** [comment]
You probably didn't mean to do an ARM build. 🙂 

Test builds are under https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-jammy-unprovisioned-gcc-cmake-experimental-packaging/. Not working yet.

**Comment by BetsyMcPhail** [comment]
Arg, I did not. Thanks for catching that

**Comment by mwoehlke-kitware** [comment]
*Working* build: https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-jammy-unprovisioned-gcc-cmake-experimental-packaging/6/

Artifacts:
- https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.20240410.204125%2Bgit37254ee5-jammy.tar.gz
- https://drake-packages.csail.mit.edu/drake/experimental/drake-dev_0.0.20240410.204125%2Bgit37254ee5-1_amd64-jammy.deb

We still need to try to verify that these are "okay".

**Comment by mwoehlke-kitware** [comment]
Okay, #​6 is missing bits due to not getting `--config=packaging` passed in as happens in Bazel-land. Hopefully fixed in https://drake-jenkins.csail.mit.edu/view/CMake/job/linux-jammy-unprovisioned-gcc-cmake-experimental-packaging/7/. Will update this with artifacts when available.

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-:-NvDFbX8DRYDKalLi9wK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by BetsyMcPhail — APPROVED** [review]
+@jwnimmer-tri for review next week

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-:-NvDFgNwEU63LfQRvwKx:bv89s5f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by mwoehlke-kitware** [comment]
FYI, I compared the file listings of the above packages to `0.0.20240410.171728+git37254ee5` (from Continuous), excluding time stamps.

For the `.tar`s:
```diff
diff --git a/bazel.bom b/cmake.bom
index 0c77800..fcd651d 100644
--- a/bazel.bom
+++ b/cmake.bom
@@ -155,7 +155,7 @@ drwxrwxr-x ubuntu/ubuntu      0 drake/share/doc/lcm/
 -rw-rw-r-- ubuntu/ubuntu    233 2023-04-19 13:49 drake/share/doc/lcm/AUTHORS
 drwxrwxr-x ubuntu/ubuntu      0 drake/share/doc/drake/
 -rw-rw-r-- ubuntu/ubuntu   1698 drake/share/doc/drake/LICENSE.TXT
--rw-rw-r-- ubuntu/ubuntu     72 drake/share/doc/drake/VERSION.TXT
+-rw-r--r-- ubuntu/ubuntu     73 drake/share/doc/drake/VERSION.TXT
 drwxrwxr-x ubuntu/ubuntu      0 drake/share/doc/crate__once_cell-1.19.0/
 -rw-r--r-- ubuntu/ubuntu  10847 2006-07-23 21:21 drake/share/doc/crate__once_cell-1.19.0/LICENSE-APACHE
 drwxrwxr-x ubuntu/ubuntu      0 drake/share/doc/fcl_internal/
```

For the `.deb`s:
```diff
diff --git a/bazel.bom b/cmake.bom
index 6eaca6c..b39fe83 100644
--- a/bazel.bom
+++ b/cmake.bom
@@ -1327,7 +1327,7 @@ drwxr-xr-x root/root         0 ./opt/drake/share/doc/curl_internal/
 -rw-r--r-- root/root      1088 ./opt/drake/share/doc/curl_internal/COPYING
 drwxr-xr-x root/root         0 ./opt/drake/share/doc/drake/
 -rw-r--r-- root/root      1698 ./opt/drake/share/doc/drake/LICENSE.TXT
--rw-r--r-- root/root        72 ./opt/drake/share/doc/drake/VERSION.TXT
+-rw-r--r-- root/root        73 ./opt/drake/share/doc/drake/VERSION.TXT
 drwxr-xr-x root/root         0 ./opt/drake/share/doc/fcl_internal/
 -rw-r--r-- root/root      1647 ./opt/drake/share/doc/fcl_internal/LICENSE
 drwxr-xr-x root/root         0 ./opt/drake/share/doc/gflags/
@@ -1560,6 +1560,6 @@ drwxr-xr-x root/root         0 ./usr/
 drwxr-xr-x root/root         0 ./usr/share/
 drwxr-xr-x root/root         0 ./usr/share/doc/
 drwxr-xr-x root/root         0 ./usr/share/doc/drake-dev/
--rw-r--r-- root/root       210 ./usr/share/doc/drake-dev/changelog.Debian.gz
+-rw-r--r-- root/root       209 ./usr/share/doc/drake-dev/changelog.Debian.gz
 -rw-r--r-- root/root        55 ./usr/share/doc/drake-dev/copyright
 lrwxrwxrwx root/root         0 ./opt/drake/lib/libtbb.so.12 -> libtbb.so.12.8
```

The permissions on `VERSION.TXT` changed. The size change seems to be because the current file lacks a terminal newline (so, an improvement). The size change of `changelog.Debian.gz` is *probably*(?) harmless.

From the Bazel package:
```
$ cat drake/share/doc/drake/VERSION.TXT
0.0.20240410.171728+git37254ee5 37254ee53a75a1215f1b9f224f5b86b3c58ec314$
```

From the CMake package:
```
$ cat drake/share/doc/drake/VERSION.TXT 
0.0.20240411.154536+git37254ee5 37254ee53a75a1215f1b9f224f5b86b3c58ec314
$ 
```

**Comment by jwnimmer-tri** [comment]
The only other thing to cross-check is the `*.deb` metadata (control file).  Since it's auto-gen by `alien` I can't imagine how it would differ, but worth checking.  I'm happy to check next week myself, too.  No rush.

**Comment by mwoehlke-kitware** [comment]
> The only other thing to cross-check is the `*.deb` metadata (control file)

How does one do that?

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: from a somewhat quick skim.

> How does one do that?

I just open the file in emacs and magic happens, I can browse everything interactively.  For non-emacs, I think on the command line `dpkg-deb -e` will extract the control data.

> Reviewed 7 of 7 files at r2, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-:-NvJFcKS8QUv3UGPeKQd:bati320)* status: all files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`driver/platform.cmake` line 99 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-NvJDt8Z6ROI3LUGbe3h:-NvJDt8Z6ROI3LUGbe3i:b-edh6i7) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/1c53e6d5d6d1718a8c2c2231ab43513c0bf757da/driver/platform.cmake#L99)):*
> ```CMake
>      endif()
>   elseif(PACKAGE)
>     set(PROVISION_ARGS "--without-test-only")
> ```

BTW This will become deadwood after we retire Bazel packaging, right?  Do we need a TODO somewhere or anything?

Possibly swapping `if(PACKAGE)` to the top of the if-elseif chain would simplify things and avoid any future deadwood?  Reordering the two cases seems like then we don't need any new code.

**Comment by mwoehlke-kitware** [comment]
*[`driver/platform.cmake` line 99 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-NvJDt8Z6ROI3LUGbe3h:-NvXQY__5lkBnIHXIoiV:b-x4j3zi) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/1c53e6d5d6d1718a8c2c2231ab43513c0bf757da/driver/platform.cmake#L99)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This will become deadwood after we retire Bazel packaging, right?  Do we need a TODO somewhere or anything?

Possibly swapping `if(PACKAGE)` to the top of the if-elseif chain would simplify things and avoid any future deadwood?  Reordering the two cases seems like then we don't need any new code.
</blockquote></details>

Correct. I have a local change that adds a note to nuke this. Probably I'll go over the entire Bazel logic looking for packaging-related bits. Is that sufficient or do you think we need to do something else?

**Review by jwnimmer-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

___
*[`driver/platform.cmake` line 99 at r7](https://reviewable.io/reviews/RobotLocomotion/drake-ci/280#-NvJDt8Z6ROI3LUGbe3h:-NvXRSOJBuR-2Jxw8sY3:b-ra74ya) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/1c53e6d5d6d1718a8c2c2231ab43513c0bf757da/driver/platform.cmake#L99)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Correct. I have a local change that adds a note to nuke this. Probably I'll go over the entire Bazel logic looking for packaging-related bits. Is that sufficient or do you think we need to do something else?
</blockquote></details>

Fine by me.

**Pull request merged**
