### PR TITLE
Refactor how Drake package version is set

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Extract the logic to determine the Drake version from points of use into a new helper step. This removes duplication and inconsistency between wheels and other packages and allows for some logic simplification.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/270)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
*[`driver/configurations/common/step-set-package-version.cmake` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/270#-NtzQZr7EA4HVC5WcYpo:-NtzQZr7EA4HVC5WcYpp:btupw60) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b5de04432ad41ea12e08d4db79063220d73bddc3/driver/configurations/common/step-set-package-version.cmake#L58)):*
> ```CMake
>   elseif(GIT_REV_PARSE_RESULT_VARIABLE EQUAL 0)
>     set(DASHBOARD_PACKAGE_COMMIT "${GIT_REV_PARSE_OUTPUT_VARIABLE}")
>     set(DASHBOARD_DRAKE_VERSION "0.0.${DASHBOARD_PACKAGE_DATE_TIME}+git${DASHBOARD_PACKAGE_COMMIT}")
> ```

Nit this results in links to filenames such as `-- Upload complete: [https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.20240326.151331%2Bgit6238c107-mac-arm64.tar.gz](https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.20240326.151331%2Bgit6238c107-mac-arm64.tar.gz)` The `%2B` reads a bit confusing

**Comment by mwoehlke-kitware** [comment]
> Nit [...] The %2B reads a bit confusing

We can't do anything about URI encoding, nor do I consider not following PEP 440 an option. Thus, our choices are a) live with it, or b) don't include the git SHA in the version.

**Comment by BetsyMcPhail** [comment]
*[`driver/configurations/common/step-set-package-version.cmake` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ci/270#-NtzQZr7EA4HVC5WcYpo:-Nu4gTlU3Ak25k2oryo1:brexffk) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/b5de04432ad41ea12e08d4db79063220d73bddc3/driver/configurations/common/step-set-package-version.cmake#L58)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit this results in links to filenames such as `-- Upload complete: [https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.20240326.151331%2Bgit6238c107-mac-arm64.tar.gz](https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.20240326.151331%2Bgit6238c107-mac-arm64.tar.gz)` The `%2B` reads a bit confusing
</blockquote></details>

Per comment above, I'm fine with living with this.

**Comment by BetsyMcPhail** [comment]
Let's try testing just this change (without the drake PR):
https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging/7/
https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release/4/
https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-jammy-unprovisioned-gcc-bazel-experimental-packaging/19/
https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-jammy-unprovisioned-gcc-wheel-experimental-release/10/

**Comment by BetsyMcPhail** [comment]
Just this PR again:
https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging/9/
https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release/6/
https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-jammy-unprovisioned-gcc-bazel-experimental-packaging/21/
https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-jammy-unprovisioned-gcc-wheel-experimental-release/12/

**Comment by BetsyMcPhail** [comment]
Jammy packaging and wheel jobs completed successfully and I confirmed the filenames and contents of VERSION.txt are as expected.

**Review by BetsyMcPhail — APPROVED** [review]
Likewise, Mac packaging and wheel jobs look okay.

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/270#-:-NuV8HVs21dsKIlgsyyY:b-ms68lp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Pull request merged**
