### PR TITLE
Add support for Mac / Bazel / Everything build

### PR DESCRIPTION
**Pull request by BetsyMcPhail**

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-mac-clang-bazel-experimental-everything-release-12&field2=buildstarttime&compare2=84&value2=now

**Comment by BetsyMcPhail** [comment]
PTAL @jamiesnape

**Comment by jamiesnape** [comment]
Delegating to @mwoehlke-kitware for review, but you would probably want to substitute `fatal()` for `message(FATAL_ERROR)`: https://github.com/RobotLocomotion/drake-ci/blob/master/driver/functions.cmake#L46-L55

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware can you take another look at this? Gurobi needed to be installed as a system library on OS X, so there's not much set-up that the CI script needs to do now.

**Comment by jamiesnape** [comment]
Seems fine. Merged.

**Pull request merged**
