### PR TITLE
Updates necessary to run jobs on Sequoia

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21910
Related to https://github.com/RobotLocomotion/drake/issues/22089

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/297)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
https://drake-jenkins.csail.mit.edu/view/Mac%20Sequoia%20Unprovisioned/job/mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release/3/

**Comment by BetsyMcPhail** [comment]
https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release/51/

**Review by BetsyMcPhail — COMMENTED** [review]
https://drake-jenkins.csail.mit.edu/view/Mac%20Sequoia%20Unprovisioned/job/mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release/4/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/297#-:-OArl6qVC5Lvxh4Naeqi:bsxjbk3)* status: 0 of 1 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
Sequoia (doesn't pass but gets pass initial setup): https://drake-jenkins.csail.mit.edu/view/Mac%20Sequoia%20Unprovisioned/job/mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release/7/
Sonoma: https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release/52

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/297#-:-OAsXJaD0SBEGWxWRMOD:b-o5qijm)* status: 0 of 3 files reviewed, all discussions resolved

**Review by BetsyMcPhail — COMMENTED** [review]
+@williamjallen for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/297#-:-OAsXZIV7LxfpZoCRfTv:b-fbdr6k)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @williamjallen)

**Review by williamjallen — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Pull request merged**
