### PR TITLE
Generate a list of subprojects to send to CDash

### PR DESCRIPTION
**Pull request by BetsyMcPhail**

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
CI testing: https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-everything/6543

**Comment by BetsyMcPhail** [comment]
CI testing: https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-everything/6548

**Comment by BetsyMcPhail** [comment]
This generates subprojects as expected with no errors in the output (on Linux, anyway, still need to test on Mac). However, adding subprojects breaks our link from Jenkins.

**Comment by jwnimmer-tri** [comment]
Hmm.  I just noticed this PR from 2018 hanging around -- @BetsyMcPhail @jamiesnape can we close this now?

**Comment by BetsyMcPhail** [comment]
Yes, closing now

**Pull request closed without merging**
