### PR TITLE
Remove x86 Monterey support

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21140

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/282)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/282#-:-NwBHm9704dY_foY-k5W:bnyvoyh)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @mwoehlke-kitware)

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri adding you for review to confirm whether or not GHA builds will need any of this logic from drake-ci. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/282#-:-NwBaT4D3w7xVyd-Y-Fo:b87uvae)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jwnimmer-tri and @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
Thanks.  It's fine to purge it all.  I can always pull up this commit after the fact and copy-paste what I need later.  The GHA stuff doesn't use CMake for top-level scripting anyway.  (It's [here](https://github.com/jwnimmer-tri/drake_github_workflow_prototype/tree/main/.github) if you're curious.)

**Comment by mwoehlke-kitware** [comment]
@jwnimmer-tri, to be clear, this implies we don't care about being able to see mac x86 on CDash?

**Comment by jwnimmer-tri** [comment]
Yes, that's correct and fine.  (For one thing, we will no longer be running any tests on mac x86 anyway, and the general "keep track of which builds have finished" stuff in CDash isn't really that useful in the case of the wheels builds.)

**Review by mwoehlke-kitware — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/282#-:-NwBmnEqEKB9dFdK6bpD:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Pull request merged**
