### PR TITLE
Use rollup bazel targets for drake docs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Takes advantage of two new Drake BUILD rules:
- https://github.com/RobotLocomotion/drake/pull/14583
- https://github.com/RobotLocomotion/drake/pull/14587

Towards https://github.com/RobotLocomotion/drake/issues/13832.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for review, please.

**Comment by jamiesnape** [comment]
Can you push a copy of this to a branch of this repo (you should have permission) so I can test it?

**Comment by jwnimmer-tri** [comment]
Sure -- https://github.com/RobotLocomotion/drake-ci/tree/doc-test should be it.

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-experimental-documentation/21/

**Review by jamiesnape — APPROVED** [review]
If the `doxygen_scratch` were not a subdirectory of `share/doc/drake` (i.e., the directory pushed to GitHub Pages) it would make me a little more comfortable, but I guess that has always been the case, and I just do not notice.

**Comment by jamiesnape** [comment]
I will let you merge, since I am not sure if you want to squash the commits (I have no preference).

**Comment by jwnimmer-tri** [comment]
Don't mind much either way, but I'll keep them separate in case of needing a revert later on.

**Comment by jwnimmer-tri** [comment]
> If the doxygen_scratch were not a subdirectory of share/doc/drake (i.e., the directory pushed to GitHub Pages) it would make me a little more comfortable, but I guess that has always been the case, and I just did not notice.

I agree.  (To be precise, I _might_ have made it a little worse with this PR.)  Anyway, that's the kind of thing I want to improve in Drake now that we have a more direct point of entry.

**Pull request merged**
