### PR TITLE
complain if kcov_tool fails

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
I'll be keeping this in draft form for a bit. it turns out that kcov has been failing for two reasons: (1) kcov_tool bugs fixed in https://github.com/RobotLocomotion/drake/pull/21859, and (2) `bazel_tools` implicitly depends on `zip`, and accidentally deletes coverage data if `zip` is absent.

So: I will add `zip` to Drake dependencies, then ask for updated images, and *then* come back to polishing these error checks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O5Ytj14BNwFUg0q15qy:b-k17f8l)* status: 0 of 1 files reviewed, all discussions resolved

**Review by rpoyner-tri — COMMENTED** [review]
Request for new images is here: https://github.com/RobotLocomotion/drake/issues/21865

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O5ZHqmZ6-x8f311Cahx:b-ksitlu)* status: 0 of 1 files reviewed, all discussions resolved

**Review by rpoyner-tri — COMMENTED** [review]
FWIW, https://github.com/bazelbuild/bazel/issues/23479 is also now fixed and slated for bazel 7.4.0, but we still should have images that contain `zip`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O61yaON6R53e81oWdfq:beve2hh)* status: 0 of 1 files reviewed, all discussions resolved

**Review by rpoyner-tri — COMMENTED** [review]
Image updates are done, but the Jammy nodes are still running the old one. Will wait until they are updated, and then run an end-to-end test before trying to merge.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O6cEc-B42Fe2eVQkb6s:bo9wszi)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Review by rpoyner-tri — COMMENTED** [review]
Things are in good shape now. For examples of success and failure with this changes, see these build logs:
* success: https://drake-jenkins.csail.mit.edu/job/linux-jammy-clang-bazel-experimental-coverage/33/
* failure: https://drake-jenkins.csail.mit.edu/job/linux-jammy-clang-bazel-experimental-coverage/31/

At `r2`, I've reverted the build target changes that made the above test builds conveniently short.

+@BetsyMcPhail for review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O6gBkvz4c4tqgZMX0WW:bod1jbd)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
Sorry for the confusion, I was experimenting and accidentally pushed to this branch. I was hoping to get a cleaner failure, with a report of the command, push the results to CDash, etc. I do have a WIP (#290) that should be ready soon. Should I push to this branch directly?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O6wMQmh8tdRMCE7MfAO:bvxnuuq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
Sure, pushing here is fine. Let me know if you need me to help test, or anything.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O6wP3NC0ImQ6oXpfSsJ:b-er0ih)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288)* status: all files reviewed, 1 unresolved discussion (waiting on @BetsyMcPhail and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-O6wRorN8oMH6oq1PF-Z:-O6wRorN8oMH6oq1PF-_:b-vi2oky) (no related file):*
Just adding a blocked discussion so it doesn't get merged before Betsy is satisfied.

___

**Review by BetsyMcPhail — COMMENTED** [review]
@rpoyner-tri how do these test results look to you?

Test at r4 (with small change to speed up testing) and breaking change in drake (https://github.com/RobotLocomotion/drake/pull/21915): https://drake-jenkins.csail.mit.edu/view/Coverage/job/linux-jammy-clang-bazel-experimental-coverage/37/

Test at r4 with drake master: https://drake-jenkins.csail.mit.edu/view/Coverage/job/linux-jammy-clang-bazel-experimental-coverage/38/

+@mwoehlke-kitware for CMake code review
 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O6wso574m6Zvdn1fMZT:b-lvs4cu)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O7-V9Cu9Vg2VV3e5DZI:bg7igkv)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @BetsyMcPhail and @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
Nested `if/else` chains aren't entirely unprecedented. The only obvious alternative would be that, in many other places, rather than nesting, each subsequent step is guarded with `if(NOT DASHBOARD_UNSTABLE)`. However, I'm guessing that in this case we want to submit even if a prior failure occurred, so that technique would not be appropriate?

:lgtm: 

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O7j0jRJ8O28Ms4LI_6_:b-xyxo3j)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @rpoyner-tri)

___
*[`driver/configurations/bazel/step-build.cmake` line 167 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-O7izczyBukI-Z4PKF_J:-O7izczyBukI-Z4PKF_K:bwubl8e) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/c54b91e4919682052640b679549a7f7bb3e2ccc0/driver/configurations/bazel/step-build.cmake#L167)):*
> ```CMake
>       endif()
> 
>       if(DASHBOARD_SUBMIT)
> ```

FYI, this gets duplicated _a lot_. At some point it might be worth refactoring this into a helper function.

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-:-O7j7UAl9JG3t683984Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rpoyner-tri)

___
*[`driver/configurations/bazel/step-build.cmake` line 167 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-O7izczyBukI-Z4PKF_J:-O7j7Mq35RgrYsMjxGDJ:b-2fggfr) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/c54b91e4919682052640b679549a7f7bb3e2ccc0/driver/configurations/bazel/step-build.cmake#L167)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, this gets duplicated _a lot_. At some point it might be worth refactoring this into a helper function.
</blockquote></details>

Not a bad idea, let's leave this for future work so these checks can get in.

**Comment by mwoehlke-kitware** [comment]
*[`driver/configurations/bazel/step-build.cmake` line 167 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ci/288#-O7izczyBukI-Z4PKF_J:-O7j7rQy06u_1h6TKKMu:b-87lkir) ([raw file](https://github.com/RobotLocomotion/drake-ci/blob/c54b91e4919682052640b679549a7f7bb3e2ccc0/driver/configurations/bazel/step-build.cmake#L167)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Not a bad idea, let's leave this for future work so these checks can get in.
</blockquote></details>

Right; I didn't intend for this PR to do so. Note "at some point". :slightly_smiling_face:

**Pull request merged**
