### PR TITLE
Make the memcheck build yellow in Jenkins if there are defects

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
CTest will now report the defect count. If it is greater than 0, report job as unstable.

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
PTAL @jamiesnape

**Comment by jamiesnape** [comment]
Can you fix up the commit author?

**Comment by BetsyMcPhail** [comment]
Oops. Author is updated

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/job/mac-clang-ninja-experimental/174/

**Comment by jamiesnape** [comment]
Can you resolve the merge conflicts?

**Pull request merged**
