### PR TITLE
Only supply cache max-age for nightly and continuous "latest"

### PR DESCRIPTION
**Pull request by svenevs**
`s3 cp --cache-control max-age={max_age}` does not control artifact expiration, it sets the Max-Age http header for hinting to browsers when the cache has expired.  For nightly this is set to 18 hours, for continuous 30 minutes.

AFAICT this is what we discussed.  Relates: https://github.com/RobotLocomotion/drake/pull/17413

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/166)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@mwoehlke-kitware for review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-:-N57XQm914nF9Rrd6oQc:bwq5xyt)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N57Y-IcA1sFKKuRKTRC:-N57Y-IcA1sFKKuRKTRD:bh3b4j0) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L97)):*
> ```Python
> 
>     raise ValueError(
>         f"max_age only supports nightly and continuous: {options}")
> ```

Working, job logs / artifacts to inspect before considering good:

- Nightly: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-snopt-mosek-release/71/ (should not interfere with release, wheels are rebuilt manually for release playbook)
- Continuous: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-mosek-packaging/279/ (queued)
- Experimental: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/27/

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/166)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5AjV7zD0hrcAc_I9Ch:-N5CaK5dBqOcjAnx8vHH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L84)):*
> ```Python
> def max_age(options):
>     """
>     Return the desired Max-Age browser cache duration in seconds as an int.
> ```

Done.
___
*[`tools/upload-to-aws.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5AjjN12Hlr4xwQ7nf5:-N5CaDo4C5E22sXHpL-J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L97)):*
> ```Python
> 
>     raise ValueError(
>         f"max_age only supports nightly and continuous: {options}")
> ```

Done.
___
*[`tools/upload-to-aws.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N57Y-IcA1sFKKuRKTRC:-N5CaqqlAP5K-SB3EcCx:b1xsu4x) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L97)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, job logs / artifacts to inspect before considering good:

- Nightly: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-snopt-mosek-release/71/ (should not interfere with release, wheels are rebuilt manually for release playbook)
- Continuous: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-mosek-packaging/279/ (queued)
- Experimental: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/27/
</blockquote></details>

New builds:

- Nightly: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-snopt-mosek-release/73/
- Continuous: https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur%20Unprovisioned/job/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-mosek-packaging/283/ (queued)
- https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/28/
___
*[`tools/upload-to-aws.py` line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5AkZ4p4RWpLQoET0Oe:-N5Ca0oUB8nPc1LshbND:b-soaax8) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, the reason I used `expiration` everywhere else is to not shadow a function with a parameter. FWIW, even with our revised understanding, I would still argue that name is sufficiently accurate.
</blockquote></details>

Done, reverted back to `expiration`.  It's not exactly _expiration_, but it's also _expiration_.  Works for me, docs on `max_age` function make it clear enough :upside_down_face:
___
*[`tools/upload-to-aws.py` line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5Ak6229BFx2seqIzWl:-N5C__BS92taZjt2llhU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L114)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

(Much more commonly used; 21 hits vs. only one, and that in Skylark... Likewise on the next line.)
</blockquote></details>

Done.
___
*[`tools/upload-to-aws.py` line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5AkwkR5uBgplPRsG4x:-N5C_QKO4mzX0v-s8Q8a:b-lb4ibt) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L173)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

For consistency:
</blockquote></details>

Done, got one other in there too in the docstring, `"latest"` isn't in the file anymore only `'latest'`.

**Review by mwoehlke-kitware — CHANGES_REQUESTED** [review]
LGTM aside from one minor oversight :slightly_smiling_face:.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-:-N5FmKHx9ObjMJh4A2KV:b-ebcqkd)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/upload-to-aws.py` line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5AkZ4p4RWpLQoET0Oe:-N5Flr6cB8IAb5TTnbV0:b-nx81j8) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L100)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, reverted back to `expiration`.  It's not exactly _expiration_, but it's also _expiration_.  Works for me, docs on `max_age` function make it clear enough :upside_down_face:
</blockquote></details>

...and docs here also :slightly_smiling_face:.
___
*[`tools/upload-to-aws.py` line 115 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5Fm-xmDYziu9bgnRpt:-N5Fm-xmDYziu9bgnRpu:bpy9zbz) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/76cbc2a0d99aa95cc30fc9b916688fa09b5ffc0c/tools/upload-to-aws.py#L115)):*
> ```Python
>     if expiration is not None:
>         command += ['--cache-control', f'max-age={expiration}']
>     command.extend([path, aws_uri(name, options)])
> ```

Missed a spot :slightly_smiling_face:.



_Suggestion:_
```Python
command += [path, aws_uri(name, options)]
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ci/166)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`tools/upload-to-aws.py` line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5AkZ4p4RWpLQoET0Oe:-N5G8bXz-soAYzi5sLE8:b-i4h85c) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/6531a299886660090f27cd0e6ce17a07100410df/tools/upload-to-aws.py#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...and docs here also :slightly_smiling_face:.
</blockquote></details>

True :upside_down_face: 
___
*[`tools/upload-to-aws.py` line 115 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ci/166#-N5Fm-xmDYziu9bgnRpt:-N5G8UqP-6JIltDsaS3B:b1jqk01) ([raw file](https://github.com/robotlocomotion/drake-ci/blob/76cbc2a0d99aa95cc30fc9b916688fa09b5ffc0c/tools/upload-to-aws.py#L115)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Missed a spot :slightly_smiling_face:.
</blockquote></details>

Done.  Gah! IT WAS RIGHT NEXT TO IT how embarrassing xD

**Pull request merged**
